//! GENERATED by fluessig bindgen from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

use magnus::{function, method, prelude::*, Error, Ruby};
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

fn rberr(e: impl std::fmt::Display) -> Error {
    let ruby = magnus::Ruby::get().expect("disponent called outside the Ruby GVL");
    Error::new(ruby.exception_runtime_error(), e.to_string())
}

use std::ffi::c_void;
use std::ptr;

/// Run `func` with the Ruby GVL released; returns its result once the GVL is
/// re-acquired. `func` MUST NOT touch any Ruby object (no Value/alloc) — extract
/// the poll result here, act on it (yield/raise) only after this returns.
fn without_gvl<F, R>(func: F) -> R
where
    F: FnOnce() -> R, // no Send bound: runs on the same OS thread
{
    unsafe extern "C" fn trampoline<F, R>(data: *mut c_void) -> *mut c_void
    where
        F: FnOnce() -> R,
    {
        let slot = &mut *(data as *mut Option<F>);
        let f = slot.take().expect("gvl closure already consumed");
        Box::into_raw(Box::new(f())) as *mut c_void
    }
    let mut slot: Option<F> = Some(func);
    let result_ptr = unsafe {
        rb_sys::rb_thread_call_without_gvl(
            Some(trampoline::<F, R>),
            &mut slot as *mut Option<F> as *mut c_void,
            None,
            ptr::null_mut(),
        )
    };
    *unsafe { Box::from_raw(result_ptr as *mut R) }
}

#[derive(Clone, Copy, PartialEq)]
pub enum EnvKind {
    Local,
    ExeDev,
    Modal,
    ClaudeCodeWeb,
    Custom,
}
impl EnvKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "local" => Ok(Self::Local),
            "exe_dev" => Ok(Self::ExeDev),
            "modal" => Ok(Self::Modal),
            "claude_code_web" => Ok(Self::ClaudeCodeWeb),
            "custom" => Ok(Self::Custom),
            other => Err(anyhow::anyhow!("unknown EnvKind: {other} (expected local | exe_dev | modal | claude_code_web | custom)"))
        }
    }
}
impl EnvKind {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::ExeDev => "exe_dev",
            Self::Modal => "modal",
            Self::ClaudeCodeWeb => "claude_code_web",
            Self::Custom => "custom",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for EnvKind {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for EnvKind {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for EnvKind {}

#[derive(Clone, Copy, PartialEq)]
pub enum SessionState {
    Queued,
    Provisioning,
    Running,
    NeedsInput,
    Completed,
    Failed,
    Cancelled,
    Lost,
}
impl SessionState {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "queued" => Ok(Self::Queued),
            "provisioning" => Ok(Self::Provisioning),
            "running" => Ok(Self::Running),
            "needs_input" => Ok(Self::NeedsInput),
            "completed" => Ok(Self::Completed),
            "failed" => Ok(Self::Failed),
            "cancelled" => Ok(Self::Cancelled),
            "lost" => Ok(Self::Lost),
            other => Err(anyhow::anyhow!("unknown SessionState: {other} (expected queued | provisioning | running | needs_input | completed | failed | cancelled | lost)"))
        }
    }
}
impl SessionState {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Provisioning => "provisioning",
            Self::Running => "running",
            Self::NeedsInput => "needs_input",
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
            Self::Lost => "lost",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for SessionState {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for SessionState {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for SessionState {}

#[derive(Clone, Copy, PartialEq)]
pub enum ExitReason {
    Ok,
    Error,
    Signal,
    Timeout,
    Budget,
    Setup,
    Unknown,
}
impl ExitReason {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "ok" => Ok(Self::Ok),
            "error" => Ok(Self::Error),
            "signal" => Ok(Self::Signal),
            "timeout" => Ok(Self::Timeout),
            "budget" => Ok(Self::Budget),
            "setup" => Ok(Self::Setup),
            "unknown" => Ok(Self::Unknown),
            other => Err(anyhow::anyhow!("unknown ExitReason: {other} (expected ok | error | signal | timeout | budget | setup | unknown)"))
        }
    }
}
impl ExitReason {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::Error => "error",
            Self::Signal => "signal",
            Self::Timeout => "timeout",
            Self::Budget => "budget",
            Self::Setup => "setup",
            Self::Unknown => "unknown",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for ExitReason {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for ExitReason {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for ExitReason {}

#[derive(Clone, Copy, PartialEq)]
pub enum IsolationKind {
    None,
    Worktree,
    Container,
    Vm,
}
impl IsolationKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "none" => Ok(Self::None),
            "worktree" => Ok(Self::Worktree),
            "container" => Ok(Self::Container),
            "vm" => Ok(Self::Vm),
            other => Err(anyhow::anyhow!(
                "unknown IsolationKind: {other} (expected none | worktree | container | vm)"
            )),
        }
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum TemplateKind {
    VmImage,
    ContainerImage,
}
impl TemplateKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "vm_image" => Ok(Self::VmImage),
            "container_image" => Ok(Self::ContainerImage),
            other => Err(anyhow::anyhow!(
                "unknown TemplateKind: {other} (expected vm_image | container_image)"
            )),
        }
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum CapabilityKind {
    Dispatch,
    Interact,
    ObserveStream,
    ObservePoll,
    ListSessions,
    Resume,
    Cancel,
    Teardown,
    IsolationWorktree,
    IsolationContainer,
    IsolationVm,
    Templates,
    ArtifactFetch,
    UsageReport,
}
impl CapabilityKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "dispatch" => Ok(Self::Dispatch),
            "interact" => Ok(Self::Interact),
            "observe_stream" => Ok(Self::ObserveStream),
            "observe_poll" => Ok(Self::ObservePoll),
            "list_sessions" => Ok(Self::ListSessions),
            "resume" => Ok(Self::Resume),
            "cancel" => Ok(Self::Cancel),
            "teardown" => Ok(Self::Teardown),
            "isolation_worktree" => Ok(Self::IsolationWorktree),
            "isolation_container" => Ok(Self::IsolationContainer),
            "isolation_vm" => Ok(Self::IsolationVm),
            "templates" => Ok(Self::Templates),
            "artifact_fetch" => Ok(Self::ArtifactFetch),
            "usage_report" => Ok(Self::UsageReport),
            other => Err(anyhow::anyhow!("unknown CapabilityKind: {other} (expected dispatch | interact | observe_stream | observe_poll | list_sessions | resume | cancel | teardown | isolation_worktree | isolation_container | isolation_vm | templates | artifact_fetch | usage_report)"))
        }
    }
}
impl CapabilityKind {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Dispatch => "dispatch",
            Self::Interact => "interact",
            Self::ObserveStream => "observe_stream",
            Self::ObservePoll => "observe_poll",
            Self::ListSessions => "list_sessions",
            Self::Resume => "resume",
            Self::Cancel => "cancel",
            Self::Teardown => "teardown",
            Self::IsolationWorktree => "isolation_worktree",
            Self::IsolationContainer => "isolation_container",
            Self::IsolationVm => "isolation_vm",
            Self::Templates => "templates",
            Self::ArtifactFetch => "artifact_fetch",
            Self::UsageReport => "usage_report",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for CapabilityKind {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for CapabilityKind {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for CapabilityKind {}

#[derive(Clone, Copy, PartialEq)]
pub enum EventKind {
    State,
    Message,
    ToolCall,
    ToolResult,
    Log,
    Usage,
    Artifact,
    Raw,
    Mail,
}
impl EventKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "state" => Ok(Self::State),
            "message" => Ok(Self::Message),
            "tool_call" => Ok(Self::ToolCall),
            "tool_result" => Ok(Self::ToolResult),
            "log" => Ok(Self::Log),
            "usage" => Ok(Self::Usage),
            "artifact" => Ok(Self::Artifact),
            "raw" => Ok(Self::Raw),
            "mail" => Ok(Self::Mail),
            other => Err(anyhow::anyhow!("unknown EventKind: {other} (expected state | message | tool_call | tool_result | log | usage | artifact | raw | mail)"))
        }
    }
}
impl EventKind {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::State => "state",
            Self::Message => "message",
            Self::ToolCall => "tool_call",
            Self::ToolResult => "tool_result",
            Self::Log => "log",
            Self::Usage => "usage",
            Self::Artifact => "artifact",
            Self::Raw => "raw",
            Self::Mail => "mail",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for EventKind {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for EventKind {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for EventKind {}

#[derive(Clone, Copy, PartialEq)]
pub enum Party {
    Manager,
    Worker,
    User,
}
impl Party {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "manager" => Ok(Self::Manager),
            "worker" => Ok(Self::Worker),
            "user" => Ok(Self::User),
            other => Err(anyhow::anyhow!(
                "unknown Party: {other} (expected manager | worker | user)"
            )),
        }
    }
}
impl Party {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Manager => "manager",
            Self::Worker => "worker",
            Self::User => "user",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for Party {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for Party {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for Party {}

#[derive(Clone, Copy, PartialEq)]
pub enum Fidelity {
    Exact,
    Derived,
    Scraped,
}
impl Fidelity {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "exact" => Ok(Self::Exact),
            "derived" => Ok(Self::Derived),
            "scraped" => Ok(Self::Scraped),
            other => Err(anyhow::anyhow!(
                "unknown Fidelity: {other} (expected exact | derived | scraped)"
            )),
        }
    }
}
impl Fidelity {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Exact => "exact",
            Self::Derived => "derived",
            Self::Scraped => "scraped",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for Fidelity {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for Fidelity {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for Fidelity {}

#[derive(Clone, Copy, PartialEq)]
pub enum ArtifactKind {
    Branch,
    PullRequest,
    Patch,
    File,
    Report,
    Url,
}
impl ArtifactKind {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "branch" => Ok(Self::Branch),
            "pull_request" => Ok(Self::PullRequest),
            "patch" => Ok(Self::Patch),
            "file" => Ok(Self::File),
            "report" => Ok(Self::Report),
            "url" => Ok(Self::Url),
            other => Err(anyhow::anyhow!("unknown ArtifactKind: {other} (expected branch | pull_request | patch | file | report | url)"))
        }
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum McpRole {
    Supervisor,
    Worker,
}
impl McpRole {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "supervisor" => Ok(Self::Supervisor),
            "worker" => Ok(Self::Worker),
            other => Err(anyhow::anyhow!(
                "unknown McpRole: {other} (expected supervisor | worker)"
            )),
        }
    }
}

#[derive(Clone, Copy, PartialEq)]
pub enum AttachTransport {
    Tmux,
    DspHold,
    Ttyd,
}
impl AttachTransport {
    pub fn parse(s: &str) -> anyhow::Result<Self> {
        match s.to_ascii_lowercase().as_str() {
            "tmux" => Ok(Self::Tmux),
            "dsp_hold" => Ok(Self::DspHold),
            "ttyd" => Ok(Self::Ttyd),
            other => Err(anyhow::anyhow!(
                "unknown AttachTransport: {other} (expected tmux | dsp_hold | ttyd)"
            )),
        }
    }
}
impl AttachTransport {
    pub fn wire(&self) -> &'static str {
        match self {
            Self::Tmux => "tmux",
            Self::DspHold => "dsp_hold",
            Self::Ttyd => "ttyd",
        }
    }
}
/// A getter returning this enum hands Ruby its wire string.
impl magnus::IntoValue for AttachTransport {
    fn into_value_with(self, ruby: &magnus::Ruby) -> magnus::Value {
        ruby.str_new(self.wire()).as_value()
    }
}
impl magnus::TryConvert for AttachTransport {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        Self::parse(&<String as magnus::TryConvert>::try_convert(val)?).map_err(rberr)
    }
}
// SAFETY: the enum owns its data (a Copy discriminant) — no borrow from
// the Ruby value survives, so it is sound in owning positions like
// `Vec<Self>` (an enum-list input param).
unsafe impl magnus::try_convert::TryConvertOwned for AttachTransport {}

#[derive(Clone)]
pub struct StateChange {
    pub from: SessionState,
    pub to: SessionState,
}

#[derive(Clone)]
pub struct AgentMessage {
    pub role: String,
    pub text: String,
}

#[derive(Clone)]
pub struct ToolCallInfo {
    pub tool: String,
    pub input: Option<String>,
}

#[derive(Clone)]
pub struct ToolResultInfo {
    pub tool: String,
    pub ok: bool,
    pub output: Option<String>,
}

#[derive(Clone)]
pub struct LogLine {
    pub line: String,
}

#[derive(Clone)]
pub struct UsageDelta {
    pub model_id: Option<String>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub cost_cents: Option<String>,
}

#[derive(Clone)]
pub struct ArtifactRef {
    pub artifact_idx: i64,
}

#[derive(Clone)]
pub struct RawObservation {
    pub source: String,
    pub data: String,
}

/// Pointer + the fields a reader needs to triage a `mail` event without
/// fetching the Message: direction (sender/recipient), the fan-out it belongs
/// to, and its topic (so a reader can group by topic for latest-wins).
#[derive(Clone)]
pub struct MailRef {
    pub message_id: String,
    pub sender: Party,
    pub recipient: Party,
    pub fanout_id: String,
    pub topic: Option<String>,
}

#[derive(Clone)]
pub struct OpenOptions {
    pub config_path: Option<String>,
    pub sink: Option<String>,
}

#[derive(Clone)]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    pub agent: Option<String>,
    pub model: Option<String>,
    pub title: Option<String>,
    pub repo: Option<String>,
    pub git_ref: Option<String>,
    pub isolation: Option<IsolationKind>,
    pub fetch_remote: Option<bool>,
    pub template: Option<String>,
    pub setup: Option<String>,
    pub timeout_secs: Option<i32>,
    pub max_budget: Option<String>,
    pub unchecked: Option<bool>,
    pub tags: Option<Vec<String>>,
    pub labels: Option<String>,
}

#[derive(Clone)]
pub struct SessionFilter {
    pub env: Option<String>,
    pub state: Option<SessionState>,
    pub dispatch_id: Option<String>,
}

/// An editor link into a session's working directory.
#[magnus::wrap(class = "Disponent::WorkspaceLink", free_immediately, size)]
#[derive(Clone)]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    pub url: Option<String>,
    pub detail: Option<String>,
}
impl WorkspaceLink {
    fn get_session_uid(&self) -> String {
        self.session_uid.clone()
    }
    fn get_available(&self) -> bool {
        self.available.clone()
    }
    fn get_url(&self) -> Option<String> {
        self.url.clone()
    }
    fn get_detail(&self) -> Option<String> {
        self.detail.clone()
    }
}

#[derive(Clone)]
pub struct EventOptions {
    pub session_uid: Option<String>,
    pub after_idx: Option<i64>,
    pub kinds: Option<Vec<EventKind>>,
}

/// Where a Manager-sent message goes. A worker never fills this: the
/// worker-role server defaults recipient = its Manager, anchored to the bound
/// session (deferred to the MCP layer). A Manager sets exactly one destination.
#[derive(Clone)]
pub struct SendTarget {
    pub tags: Option<Vec<String>>,
    pub sessions: Option<Vec<String>>,
    pub user: Option<String>,
}

/// Filter for the `messages` read. Absent fields don't constrain.
#[derive(Clone)]
pub struct MessagesFilter {
    pub fanout_id: Option<String>,
    pub recipient: Option<Party>,
    pub session_uid: Option<String>,
    pub topic: Option<String>,
    pub latest_per_topic: Option<bool>,
}

#[magnus::wrap(class = "Disponent::ReconcileReport", free_immediately, size)]
#[derive(Clone)]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}
impl ReconcileReport {
    fn get_adopted(&self) -> i32 {
        self.adopted.clone()
    }
    fn get_confirmed(&self) -> i32 {
        self.confirmed.clone()
    }
    fn get_lost(&self) -> i32 {
        self.lost.clone()
    }
    fn get_torn_down(&self) -> i32 {
        self.torn_down.clone()
    }
}

#[derive(Clone)]
pub struct McpOptions {
    pub transport: Option<String>,
    pub role: Option<McpRole>,
    pub max_depth: Option<i32>,
}

#[derive(Clone)]
pub struct DriverPlanOptions {
    pub dialect: Option<String>,
    pub tables: Option<Vec<String>>,
}

#[magnus::wrap(class = "Disponent::Statement", free_immediately, size)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
}
impl Statement {
    fn get_sql(&self) -> String {
        self.sql.clone()
    }
    fn get_params(&self) -> String {
        self.params.clone()
    }
}

/// What an environment can do: one row per (env, capability) the catalog
/// advertises. Mirrors the env_capabilities edge as a flat, returnable value
/// struct (the closed CapabilityKind vocabulary, plus open detail).
#[magnus::wrap(class = "Disponent::EnvCapability", free_immediately, size)]
#[derive(Clone)]
pub struct EnvCapability {
    pub env_slug: String,
    pub capability: CapabilityKind,
    pub detail: Option<String>,
}
impl EnvCapability {
    fn get_env_slug(&self) -> String {
        self.env_slug.clone()
    }
    fn get_capability(&self) -> CapabilityKind {
        self.capability.clone()
    }
    fn get_detail(&self) -> Option<String> {
        self.detail.clone()
    }
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[magnus::wrap(class = "Disponent::Environment", free_immediately, size)]
#[derive(Clone)]
pub struct Environment {
    pub slug: String,
    pub kind: EnvKind,
    pub display_name: Option<String>,
    pub endpoint: Option<String>,
    pub last_probed_at: Option<String>,
}
impl Environment {
    fn get_slug(&self) -> String {
        self.slug.clone()
    }
    fn get_kind(&self) -> EnvKind {
        self.kind.clone()
    }
    fn get_display_name(&self) -> Option<String> {
        self.display_name.clone()
    }
    fn get_endpoint(&self) -> Option<String> {
        self.endpoint.clone()
    }
    fn get_last_probed_at(&self) -> Option<String> {
        self.last_probed_at.clone()
    }
}

/// env × agent × model availability (from the shipped catalog + config).
#[magnus::wrap(class = "Disponent::Offering", free_immediately, size)]
#[derive(Clone)]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}
impl Offering {
    fn get_env_slug(&self) -> String {
        self.env_slug.clone()
    }
    fn get_agent_name(&self) -> String {
        self.agent_name.clone()
    }
    fn get_model_id(&self) -> String {
        self.model_id.clone()
    }
    fn get_is_default(&self) -> bool {
        self.is_default.clone()
    }
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[magnus::wrap(class = "Disponent::Session", free_immediately, size)]
#[derive(Clone)]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: SessionState,
    pub env_handle: Option<String>,
    pub attach_transport: Option<AttachTransport>,
    pub attach_endpoint: Option<String>,
    pub attach_target: Option<String>,
    pub attach_url: Option<String>,
    pub url: Option<String>,
    pub resumed_from: Option<String>,
    pub started_at: Option<String>,
    pub ended_at: Option<String>,
    pub exit_reason: Option<ExitReason>,
    pub exit_detail: Option<String>,
    pub reaped_at: Option<String>,
}
impl Session {
    fn get_uid(&self) -> String {
        self.uid.clone()
    }
    fn get_dispatch_id(&self) -> String {
        self.dispatch_id.clone()
    }
    fn get_state(&self) -> SessionState {
        self.state.clone()
    }
    fn get_env_handle(&self) -> Option<String> {
        self.env_handle.clone()
    }
    fn get_attach_transport(&self) -> Option<AttachTransport> {
        self.attach_transport.clone()
    }
    fn get_attach_endpoint(&self) -> Option<String> {
        self.attach_endpoint.clone()
    }
    fn get_attach_target(&self) -> Option<String> {
        self.attach_target.clone()
    }
    fn get_attach_url(&self) -> Option<String> {
        self.attach_url.clone()
    }
    fn get_url(&self) -> Option<String> {
        self.url.clone()
    }
    fn get_resumed_from(&self) -> Option<String> {
        self.resumed_from.clone()
    }
    fn get_started_at(&self) -> Option<String> {
        self.started_at.clone()
    }
    fn get_ended_at(&self) -> Option<String> {
        self.ended_at.clone()
    }
    fn get_exit_reason(&self) -> Option<ExitReason> {
        self.exit_reason.clone()
    }
    fn get_exit_detail(&self) -> Option<String> {
        self.exit_detail.clone()
    }
    fn get_reaped_at(&self) -> Option<String> {
        self.reaped_at.clone()
    }
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[magnus::wrap(class = "Disponent::Event", free_immediately, size)]
#[derive(Clone)]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: EventKind,
    pub fidelity: Fidelity,
    pub payload: String,
}
impl Event {
    fn get_session_uid(&self) -> String {
        self.session_uid.clone()
    }
    fn get_idx(&self) -> i64 {
        self.idx.clone()
    }
    fn get_ts(&self) -> String {
        self.ts.clone()
    }
    fn get_kind(&self) -> EventKind {
        self.kind.clone()
    }
    fn get_fidelity(&self) -> Fidelity {
        self.fidelity.clone()
    }
    fn get_payload(&self) -> String {
        self.payload.clone()
    }
}

/// One message dropped in one inbox — the manager↔worker communication
/// primitive (notes/manager-worker-comms.md). The Manager mints these addressed
/// to a worker or the user; a worker mints them addressed (implicitly) to its
/// Manager. Disponent owns these rows — no environment backs them, so reconcile
/// skips them and durability is the SQLite mirror (design §11).
#[magnus::wrap(class = "Disponent::Message", free_immediately, size)]
#[derive(Clone)]
pub struct Message {
    pub id: String,
    pub created_at: String,
    pub sender: Party,
    pub recipient: Party,
    pub session_uid: String,
    pub body: String,
    pub in_reply_to: Option<String>,
    pub fanout_id: String,
    pub topic: Option<String>,
    pub acked_at: Option<String>,
}
impl Message {
    fn get_id(&self) -> String {
        self.id.clone()
    }
    fn get_created_at(&self) -> String {
        self.created_at.clone()
    }
    fn get_sender(&self) -> Party {
        self.sender.clone()
    }
    fn get_recipient(&self) -> Party {
        self.recipient.clone()
    }
    fn get_session_uid(&self) -> String {
        self.session_uid.clone()
    }
    fn get_body(&self) -> String {
        self.body.clone()
    }
    fn get_in_reply_to(&self) -> Option<String> {
        self.in_reply_to.clone()
    }
    fn get_fanout_id(&self) -> String {
        self.fanout_id.clone()
    }
    fn get_topic(&self) -> Option<String> {
        self.topic.clone()
    }
    fn get_acked_at(&self) -> Option<String> {
        self.acked_at.clone()
    }
}

/// The `Disponent` contract — implement over the engine in `crate::core_impl`.
pub trait DisponentCore: Sized + Send + Sync + 'static {
    fn open(options: Option<OpenOptions>) -> anyhow::Result<Self>;
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn capabilities(&self) -> anyhow::Result<Vec<EnvCapability>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    fn events(&self, options: Option<EventOptions>) -> anyhow::Result<Box<dyn PollStream<Event>>>;
    fn send(
        &self,
        body: String,
        to: Option<SendTarget>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> anyhow::Result<Vec<Message>>;
    fn ack(&self, message_id: String) -> anyhow::Result<()>;
    fn messages(&self, filter: Option<MessagesFilter>) -> anyhow::Result<Vec<Message>>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
}

/// Poll-based stream from `Disponent.events`.
///
/// Primary surface: `each` — yields each event to a block, and returns an
/// `Enumerator` when called with NO block (so `.lazy`/`.map`/`.next` compose).
/// Retained surface: the `.next` poll cursor (fallible since P1) for consumers
/// that want an explicit pull rather than a block.
#[magnus::wrap(class = "Disponent::Events", free_immediately, size)]
pub struct Events {
    stream: Box<dyn PollStream<Event>>,
}
impl Events {
    // A terminal `Poll::Failed` raises a Ruby RuntimeError (mirrors node's
    // default throw-mode): the sync `.next` cursor has no error-as-event
    // surface, so a mid-stream core failure surfaces as `rberr(e)`.
    fn next(&self) -> Result<Option<Event>, Error> {
        loop {
            // GVL released around the blocking poll; the `Poll<item>` is a
            // pure-Rust value, so no Ruby object is touched while released.
            let poll = without_gvl(|| self.stream.poll(Duration::from_millis(500)));
            match poll {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None), // nil ends iteration
                Poll::Failed(e) => return Err(rberr(e)), // raises on failure
            }
        }
    }
    // Idiomatic streaming surface. With a block: yield each event, skipping
    // idle polls and ending at `Poll::Closed`. With NO block: return an
    // `Enumerator` over `each`, so `.lazy`/`.map`/`.next` compose (Ruby >= 3.1
    // for an Enumerator built from a yielding method). `Obj<Self>` is the
    // receiver so `enumeratorize` has the Ruby self value and the field is
    // still reachable via Deref. The blocking `poll` runs with the GVL
    // RELEASED (via `without_gvl` → `rb_thread_call_without_gvl`), so an
    // idling/blocking stream does not stall other Ruby threads; the Ruby
    // ops (yield/raise) stay OUTSIDE the released region. See
    // notes/async-iterable-streams-ruby.md.
    fn each(ruby: &Ruby, rb_self: magnus::typed_data::Obj<Self>) -> Result<magnus::Value, Error> {
        // No block => hand back an Enumerator so `.lazy`/`.map`/`.next` work.
        if !ruby.block_given() {
            return Ok(rb_self.enumeratorize("each", ()).as_value());
        }
        loop {
            // GVL released around the blocking poll; the `Poll<item>` is a
            // pure-Rust value, so no Ruby object is touched while released.
            // yield_value / the ErrorEvent yield / the raise all run AFTER.
            let poll = without_gvl(|| rb_self.stream.poll(Duration::from_millis(500)));
            match poll {
                Poll::Item(v) => {
                    let _: magnus::Value = ruby.yield_value(v)?;
                }
                Poll::Idle => continue,
                Poll::Closed => break,
                Poll::Failed(e) => return Err(rberr(e)), // throw-mode: raises in Ruby
            }
        }
        // `each` returns the receiver, like `Array#each`.
        Ok(rb_self.as_value())
    }
}
// Backstop: an early `break` out of the block leaves the stream
// un-exhausted, so `Drop` guarantees the core stream is closed and its
// resources released (the `close()` default is an idempotent no-op).
impl Drop for Events {
    fn drop(&mut self) {
        self.stream.close();
    }
}

/// Poll-based stream from `Disponent.driverPlan`.
///
/// Primary surface: `each` — yields each event to a block, and returns an
/// `Enumerator` when called with NO block (so `.lazy`/`.map`/`.next` compose).
/// Retained surface: the `.next` poll cursor (fallible since P1) for consumers
/// that want an explicit pull rather than a block.
#[magnus::wrap(class = "Disponent::DriverPlan", free_immediately, size)]
pub struct DriverPlan {
    stream: Box<dyn PollStream<Statement>>,
}
impl DriverPlan {
    // A terminal `Poll::Failed` raises a Ruby RuntimeError (mirrors node's
    // default throw-mode): the sync `.next` cursor has no error-as-event
    // surface, so a mid-stream core failure surfaces as `rberr(e)`.
    fn next(&self) -> Result<Option<Statement>, Error> {
        loop {
            // GVL released around the blocking poll; the `Poll<item>` is a
            // pure-Rust value, so no Ruby object is touched while released.
            let poll = without_gvl(|| self.stream.poll(Duration::from_millis(500)));
            match poll {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None), // nil ends iteration
                Poll::Failed(e) => return Err(rberr(e)), // raises on failure
            }
        }
    }
    // Idiomatic streaming surface. With a block: yield each event, skipping
    // idle polls and ending at `Poll::Closed`. With NO block: return an
    // `Enumerator` over `each`, so `.lazy`/`.map`/`.next` compose (Ruby >= 3.1
    // for an Enumerator built from a yielding method). `Obj<Self>` is the
    // receiver so `enumeratorize` has the Ruby self value and the field is
    // still reachable via Deref. The blocking `poll` runs with the GVL
    // RELEASED (via `without_gvl` → `rb_thread_call_without_gvl`), so an
    // idling/blocking stream does not stall other Ruby threads; the Ruby
    // ops (yield/raise) stay OUTSIDE the released region. See
    // notes/async-iterable-streams-ruby.md.
    fn each(ruby: &Ruby, rb_self: magnus::typed_data::Obj<Self>) -> Result<magnus::Value, Error> {
        // No block => hand back an Enumerator so `.lazy`/`.map`/`.next` work.
        if !ruby.block_given() {
            return Ok(rb_self.enumeratorize("each", ()).as_value());
        }
        loop {
            // GVL released around the blocking poll; the `Poll<item>` is a
            // pure-Rust value, so no Ruby object is touched while released.
            // yield_value / the ErrorEvent yield / the raise all run AFTER.
            let poll = without_gvl(|| rb_self.stream.poll(Duration::from_millis(500)));
            match poll {
                Poll::Item(v) => {
                    let _: magnus::Value = ruby.yield_value(v)?;
                }
                Poll::Idle => continue,
                Poll::Closed => break,
                Poll::Failed(e) => return Err(rberr(e)), // throw-mode: raises in Ruby
            }
        }
        // `each` returns the receiver, like `Array#each`.
        Ok(rb_self.as_value())
    }
}
// Backstop: an early `break` out of the block leaves the stream
// un-exhausted, so `Drop` guarantees the core stream is closed and its
// resources released (the `close()` default is an idempotent no-op).
impl Drop for DriverPlan {
    fn drop(&mut self) {
        self.stream.close();
    }
}

#[magnus::wrap(class = "Disponent", free_immediately, size)]
pub struct Disponent {
    core: Arc<crate::core_impl::DisponentImpl>,
}

impl Disponent {
    fn new(args: &[magnus::Value]) -> Result<Self, Error> {
        let config_path: Option<String> = match args.get(0).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let sink: Option<String> = match args.get(1).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let open_options_arg = OpenOptions { config_path, sink };

        Ok(Self {
            core: Arc::new(
                <crate::core_impl::DisponentImpl as DisponentCore>::open(Some(open_options_arg))
                    .map_err(rberr)?,
            ),
        })
    }
    fn environments(&self) -> Result<magnus::RArray, Error> {
        let out = self.core.environments().map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    fn refresh(&self, args: &[magnus::Value]) -> Result<magnus::RArray, Error> {
        let a = magnus::scan_args::scan_args::<(), (Option<String>,), (), (), (), ()>(args)?;
        let (env_slug,) = a.optional;

        let out = self.core.refresh(env_slug).map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    /// The offerings table: every env × agent × model the catalog knows, each
    /// flagged `isDefault` when it's the pick for a dispatch that names only the
    /// environment. Lets a consumer enumerate what can run where without reaching
    /// for the raw driver plan.
    fn offerings(&self) -> Result<magnus::RArray, Error> {
        let out = self.core.offerings().map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    /// Per-env capabilities: what each environment can do, one row per
    /// (env, capability) the catalog advertises. Lets a consumer grade backends
    /// by what they support without reaching for the raw driver plan.
    fn capabilities(&self) -> Result<magnus::RArray, Error> {
        let out = self.core.capabilities().map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    fn dispatch(&self, args: &[magnus::Value]) -> Result<Session, Error> {
        let brief: String = magnus::TryConvert::try_convert(
            args.get(0)
                .copied()
                .ok_or_else(|| rberr("wrong number of arguments"))?,
        )?;
        let env: String = magnus::TryConvert::try_convert(
            args.get(1)
                .copied()
                .ok_or_else(|| rberr("wrong number of arguments"))?,
        )?;
        let agent: Option<String> = match args.get(2).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let model: Option<String> = match args.get(3).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let title: Option<String> = match args.get(4).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let repo: Option<String> = match args.get(5).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let git_ref: Option<String> = match args.get(6).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let isolation: Option<String> = match args.get(7).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let fetch_remote: Option<bool> = match args.get(8).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let template: Option<String> = match args.get(9).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let setup: Option<String> = match args.get(10).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let timeout_secs: Option<i32> = match args.get(11).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let max_budget: Option<String> = match args.get(12).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let unchecked: Option<bool> = match args.get(13).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let tags: Option<Vec<String>> = match args.get(14).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let labels: Option<String> = match args.get(15).copied() {
            Some(v) if !v.is_nil() => Some(magnus::TryConvert::try_convert(v)?),
            _ => None,
        };
        let isolation = isolation
            .map(|s| IsolationKind::parse(&s))
            .transpose()
            .map_err(rberr)?;
        let dispatch_spec_arg = DispatchSpec {
            brief,
            env,
            agent,
            model,
            title,
            repo,
            git_ref,
            isolation,
            fetch_remote,
            template,
            setup,
            timeout_secs,
            max_budget,
            unchecked,
            tags,
            labels,
        };

        self.core.dispatch(dispatch_spec_arg).map_err(rberr)
    }
    fn session(&self, uid: String) -> Result<Option<Session>, Error> {
        self.core.session(uid).map_err(rberr)
    }
    fn sessions(&self, args: &[magnus::Value]) -> Result<magnus::RArray, Error> {
        let a = magnus::scan_args::scan_args::<
            (),
            (Option<String>, Option<String>, Option<String>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (env, state, dispatch_id) = a.optional;
        let state = state
            .map(|s| SessionState::parse(&s))
            .transpose()
            .map_err(rberr)?;
        let session_filter_arg = SessionFilter {
            env,
            state,
            dispatch_id,
        };

        let out = self
            .core
            .sessions(Some(session_filter_arg))
            .map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    /// Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.
    fn workspace_link(&self, session_uid: String) -> Result<WorkspaceLink, Error> {
        self.core.workspace_link(session_uid).map_err(rberr)
    }
    fn events(&self, args: &[magnus::Value]) -> Result<Events, Error> {
        let a = magnus::scan_args::scan_args::<
            (),
            (Option<String>, Option<i64>, Option<Vec<EventKind>>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (session_uid, after_idx, kinds) = a.optional;
        let event_options_arg = EventOptions {
            session_uid,
            after_idx,
            kinds,
        };

        Ok(Events {
            stream: self.core.events(Some(event_options_arg)).map_err(rberr)?,
        })
    }
    /// The one messaging primitive (notes/manager-worker-comms.md §6). A Manager
    /// `to` names a tagged worker subset (fan-out) or the user; recipients resolve
    /// at send time to a concrete list (a snapshot, never kept live). One Message
    /// is minted per matched session, all sharing a freshly minted `fanoutId`;
    /// `topic` (optional) is the supersession key for latest-wins (§7). Returns the
    /// Messages minted. Delivery is the reader's `events` pull; a message to a
    /// concrete live worker is also delivered best-effort to its prompt on an
    /// interact-capable env (the legacy `send` behavior, now one backend delivery).
    /// Worker self-send (recipient forced to the Manager) is a worker-role MCP
    /// concern, deferred — the core send is the Manager surface.
    fn send(&self, args: &[magnus::Value]) -> Result<magnus::RArray, Error> {
        let a = magnus::scan_args::scan_args::<
            (String,),
            (
                Option<Vec<String>>,
                Option<Vec<String>>,
                Option<String>,
                Option<String>,
                Option<String>,
            ),
            (),
            (),
            (),
            (),
        >(args)?;
        let (body,) = a.required;
        let (tags, sessions, user, in_reply_to, topic) = a.optional;
        let send_target_arg = SendTarget {
            tags,
            sessions,
            user,
        };

        let out = self
            .core
            .send(body, Some(send_target_arg), in_reply_to, topic)
            .map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    /// Acknowledge a message you received (received/handled): stamps `ackedAt`,
    /// which the Manager observes across a `fanoutId` to see "N of M acted" (§7).
    /// Idempotent.
    fn ack(&self, message_id: String) -> Result<(), Error> {
        self.core.ack(message_id).map_err(rberr)
    }
    /// Read Messages, filtered. The Manager's fan-out ack-progress view
    /// (`{fanoutId}`) and a recipient's inbox (`{recipient, sessionUid}`, optionally
    /// `latestPerTopic` for the read-side latest-wins collapse, §7).
    fn messages(&self, args: &[magnus::Value]) -> Result<magnus::RArray, Error> {
        let a = magnus::scan_args::scan_args::<
            (),
            (
                Option<String>,
                Option<String>,
                Option<String>,
                Option<String>,
                Option<bool>,
            ),
            (),
            (),
            (),
            (),
        >(args)?;
        let (fanout_id, recipient, session_uid, topic, latest_per_topic) = a.optional;
        let recipient = recipient
            .map(|s| Party::parse(&s))
            .transpose()
            .map_err(rberr)?;
        let messages_filter_arg = MessagesFilter {
            fanout_id,
            recipient,
            session_uid,
            topic,
            latest_per_topic,
        };

        let out = self
            .core
            .messages(Some(messages_filter_arg))
            .map_err(rberr)?;
        let ruby = Ruby::get().map_err(|e| rberr(e))?;
        let ary = ruby.ary_new();
        for v in out {
            ary.push(v)?;
        }
        Ok(ary)
    }
    fn cancel(&self, session_uid: String) -> Result<Session, Error> {
        self.core.cancel(session_uid).map_err(rberr)
    }
    fn resume(&self, session_uid: String) -> Result<Session, Error> {
        self.core.resume(session_uid).map_err(rberr)
    }
    fn reap(&self, session_uid: String) -> Result<Session, Error> {
        self.core.reap(session_uid).map_err(rberr)
    }
    fn reconcile(&self) -> Result<ReconcileReport, Error> {
        self.core.reconcile().map_err(rberr)
    }
    fn driver_plan(&self, args: &[magnus::Value]) -> Result<DriverPlan, Error> {
        let a = magnus::scan_args::scan_args::<
            (),
            (Option<String>, Option<Vec<String>>),
            (),
            (),
            (),
            (),
        >(args)?;
        let (dialect, tables) = a.optional;
        let driver_plan_options_arg = DriverPlanOptions { dialect, tables };

        Ok(DriverPlan {
            stream: self
                .core
                .driver_plan(Some(driver_plan_options_arg))
                .map_err(rberr)?,
        })
    }
    // @manual: wait — hand-written in lib.rs if this binding offers it.
    // @manual: serveMcp — hand-written in lib.rs if this binding offers it.
}

/// Register the Disponent class + every generated method (called from #[magnus::init]).
pub fn register(ruby: &Ruby) -> Result<(), Error> {
    let class = ruby.define_class("Disponent", ruby.class_object())?;
    let c = class.define_class("WorkspaceLink", ruby.class_object())?;
    c.define_method("session_uid", method!(WorkspaceLink::get_session_uid, 0))?;
    c.define_method("available", method!(WorkspaceLink::get_available, 0))?;
    c.define_method("url", method!(WorkspaceLink::get_url, 0))?;
    c.define_method("detail", method!(WorkspaceLink::get_detail, 0))?;
    let c = class.define_class("ReconcileReport", ruby.class_object())?;
    c.define_method("adopted", method!(ReconcileReport::get_adopted, 0))?;
    c.define_method("confirmed", method!(ReconcileReport::get_confirmed, 0))?;
    c.define_method("lost", method!(ReconcileReport::get_lost, 0))?;
    c.define_method("torn_down", method!(ReconcileReport::get_torn_down, 0))?;
    let c = class.define_class("Statement", ruby.class_object())?;
    c.define_method("sql", method!(Statement::get_sql, 0))?;
    c.define_method("params", method!(Statement::get_params, 0))?;
    let c = class.define_class("EnvCapability", ruby.class_object())?;
    c.define_method("env_slug", method!(EnvCapability::get_env_slug, 0))?;
    c.define_method("capability", method!(EnvCapability::get_capability, 0))?;
    c.define_method("detail", method!(EnvCapability::get_detail, 0))?;
    let c = class.define_class("Environment", ruby.class_object())?;
    c.define_method("slug", method!(Environment::get_slug, 0))?;
    c.define_method("kind", method!(Environment::get_kind, 0))?;
    c.define_method("display_name", method!(Environment::get_display_name, 0))?;
    c.define_method("endpoint", method!(Environment::get_endpoint, 0))?;
    c.define_method(
        "last_probed_at",
        method!(Environment::get_last_probed_at, 0),
    )?;
    let c = class.define_class("Offering", ruby.class_object())?;
    c.define_method("env_slug", method!(Offering::get_env_slug, 0))?;
    c.define_method("agent_name", method!(Offering::get_agent_name, 0))?;
    c.define_method("model_id", method!(Offering::get_model_id, 0))?;
    c.define_method("is_default", method!(Offering::get_is_default, 0))?;
    let c = class.define_class("Session", ruby.class_object())?;
    c.define_method("uid", method!(Session::get_uid, 0))?;
    c.define_method("dispatch_id", method!(Session::get_dispatch_id, 0))?;
    c.define_method("state", method!(Session::get_state, 0))?;
    c.define_method("env_handle", method!(Session::get_env_handle, 0))?;
    c.define_method(
        "attach_transport",
        method!(Session::get_attach_transport, 0),
    )?;
    c.define_method("attach_endpoint", method!(Session::get_attach_endpoint, 0))?;
    c.define_method("attach_target", method!(Session::get_attach_target, 0))?;
    c.define_method("attach_url", method!(Session::get_attach_url, 0))?;
    c.define_method("url", method!(Session::get_url, 0))?;
    c.define_method("resumed_from", method!(Session::get_resumed_from, 0))?;
    c.define_method("started_at", method!(Session::get_started_at, 0))?;
    c.define_method("ended_at", method!(Session::get_ended_at, 0))?;
    c.define_method("exit_reason", method!(Session::get_exit_reason, 0))?;
    c.define_method("exit_detail", method!(Session::get_exit_detail, 0))?;
    c.define_method("reaped_at", method!(Session::get_reaped_at, 0))?;
    let c = class.define_class("Event", ruby.class_object())?;
    c.define_method("session_uid", method!(Event::get_session_uid, 0))?;
    c.define_method("idx", method!(Event::get_idx, 0))?;
    c.define_method("ts", method!(Event::get_ts, 0))?;
    c.define_method("kind", method!(Event::get_kind, 0))?;
    c.define_method("fidelity", method!(Event::get_fidelity, 0))?;
    c.define_method("payload", method!(Event::get_payload, 0))?;
    let c = class.define_class("Message", ruby.class_object())?;
    c.define_method("id", method!(Message::get_id, 0))?;
    c.define_method("created_at", method!(Message::get_created_at, 0))?;
    c.define_method("sender", method!(Message::get_sender, 0))?;
    c.define_method("recipient", method!(Message::get_recipient, 0))?;
    c.define_method("session_uid", method!(Message::get_session_uid, 0))?;
    c.define_method("body", method!(Message::get_body, 0))?;
    c.define_method("in_reply_to", method!(Message::get_in_reply_to, 0))?;
    c.define_method("fanout_id", method!(Message::get_fanout_id, 0))?;
    c.define_method("topic", method!(Message::get_topic, 0))?;
    c.define_method("acked_at", method!(Message::get_acked_at, 0))?;
    let s = class.define_class("Events", ruby.class_object())?;
    s.define_method("next", method!(Events::next, 0))?;
    s.define_method("each", method!(Events::each, 0))?;
    let s = class.define_class("DriverPlan", ruby.class_object())?;
    s.define_method("next", method!(DriverPlan::next, 0))?;
    s.define_method("each", method!(DriverPlan::each, 0))?;
    class.define_singleton_method("new", function!(Disponent::new, -1))?;
    class.define_method("environments", method!(Disponent::environments, 0))?;
    class.define_method("refresh", method!(Disponent::refresh, -1))?;
    class.define_method("offerings", method!(Disponent::offerings, 0))?;
    class.define_method("capabilities", method!(Disponent::capabilities, 0))?;
    class.define_method("dispatch", method!(Disponent::dispatch, -1))?;
    class.define_method("session", method!(Disponent::session, 1))?;
    class.define_method("sessions", method!(Disponent::sessions, -1))?;
    class.define_method("workspace_link", method!(Disponent::workspace_link, 1))?;
    class.define_method("events", method!(Disponent::events, -1))?;
    class.define_method("send", method!(Disponent::send, -1))?;
    class.define_method("ack", method!(Disponent::ack, 1))?;
    class.define_method("messages", method!(Disponent::messages, -1))?;
    class.define_method("cancel", method!(Disponent::cancel, 1))?;
    class.define_method("resume", method!(Disponent::resume, 1))?;
    class.define_method("reap", method!(Disponent::reap, 1))?;
    class.define_method("reconcile", method!(Disponent::reconcile, 0))?;
    class.define_method("driver_plan", method!(Disponent::driver_plan, -1))?;
    Ok(())
}
