//! GENERATED by fluessig bindgen from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use std::sync::Arc;
use std::time::Duration;

fn err(e: impl std::fmt::Display) -> PyErr {
    PyRuntimeError::new_err(e.to_string())
}

/// One poll result from a core stream (the sync primitive every stream shape dresses).
pub enum Poll<T> {
    Item(T),
    Idle,
    Closed,
}

/// The one sync primitive: a blocking, timeout-bounded poll.
pub trait PollStream<T>: Send + Sync {
    fn poll(&self, timeout: Duration) -> Poll<T>;
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum EnvKind {
    Local,
    ExeDev,
    Modal,
    ClaudeCodeWeb,
    Custom,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum SessionState {
    Queued,
    Provisioning,
    Running,
    NeedsInput,
    Completed,
    Failed,
    Cancelled,
    Lost,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum ExitReason {
    Ok,
    Error,
    Signal,
    Timeout,
    Budget,
    Setup,
    Unknown,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum IsolationKind {
    None,
    Worktree,
    Container,
    Vm,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum TemplateKind {
    VmImage,
    ContainerImage,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum CapabilityKind {
    Dispatch,
    Interact,
    ObserveStream,
    ObservePoll,
    ListSessions,
    Resume,
    Cancel,
    Teardown,
    IsolationWorktree,
    IsolationContainer,
    IsolationVm,
    Templates,
    ArtifactFetch,
    UsageReport,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum EventKind {
    State,
    Message,
    ToolCall,
    ToolResult,
    Log,
    Usage,
    Artifact,
    Raw,
    Mail,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum Party {
    Manager,
    Worker,
    User,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum Fidelity {
    Exact,
    Derived,
    Scraped,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum ArtifactKind {
    Branch,
    PullRequest,
    Patch,
    File,
    Report,
    Url,
}

#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq)]
pub enum McpRole {
    Supervisor,
    Worker,
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct StateChange {
    pub from_: SessionState,
    pub to: SessionState,
}
#[pymethods]
impl StateChange {
    #[new]
    #[pyo3(signature = (from_, to))]
    fn new(from_: SessionState, to: SessionState) -> Self {
        Self { from_, to }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct AgentMessage {
    pub role: String,
    pub text: String,
}
#[pymethods]
impl AgentMessage {
    #[new]
    #[pyo3(signature = (role, text))]
    fn new(role: String, text: String) -> Self {
        Self { role, text }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ToolCallInfo {
    pub tool: String,
    pub input: Option<String>,
}
#[pymethods]
impl ToolCallInfo {
    #[new]
    #[pyo3(signature = (tool, input=None))]
    fn new(tool: String, input: Option<String>) -> Self {
        Self { tool, input }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ToolResultInfo {
    pub tool: String,
    pub ok: bool,
    pub output: Option<String>,
}
#[pymethods]
impl ToolResultInfo {
    #[new]
    #[pyo3(signature = (tool, ok, output=None))]
    fn new(tool: String, ok: bool, output: Option<String>) -> Self {
        Self { tool, ok, output }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct LogLine {
    pub line: String,
}
#[pymethods]
impl LogLine {
    #[new]
    #[pyo3(signature = (line))]
    fn new(line: String) -> Self {
        Self { line }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct UsageDelta {
    pub model_id: Option<String>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub cost_cents: Option<String>,
}
#[pymethods]
impl UsageDelta {
    #[new]
    #[pyo3(signature = (model_id=None, input_tokens=None, output_tokens=None, cost_cents=None))]
    fn new(
        model_id: Option<String>,
        input_tokens: Option<i64>,
        output_tokens: Option<i64>,
        cost_cents: Option<String>,
    ) -> Self {
        Self {
            model_id,
            input_tokens,
            output_tokens,
            cost_cents,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ArtifactRef {
    pub artifact_idx: i64,
}
#[pymethods]
impl ArtifactRef {
    #[new]
    #[pyo3(signature = (artifact_idx))]
    fn new(artifact_idx: i64) -> Self {
        Self { artifact_idx }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct RawObservation {
    pub source: String,
    pub data: String,
}
#[pymethods]
impl RawObservation {
    #[new]
    #[pyo3(signature = (source, data))]
    fn new(source: String, data: String) -> Self {
        Self { source, data }
    }
}

/// Pointer + the fields a reader needs to triage a `mail` event without
/// fetching the Message: direction (sender/recipient), the fan-out it belongs
/// to, and its topic (so a reader can group by topic for latest-wins).
#[pyclass(get_all)]
#[derive(Clone)]
pub struct MailRef {
    pub message_id: String,
    pub sender: Party,
    pub recipient: Party,
    pub fanout_id: String,
    pub topic: Option<String>,
}
#[pymethods]
impl MailRef {
    #[new]
    #[pyo3(signature = (message_id, sender, recipient, fanout_id, topic=None))]
    fn new(
        message_id: String,
        sender: Party,
        recipient: Party,
        fanout_id: String,
        topic: Option<String>,
    ) -> Self {
        Self {
            message_id,
            sender,
            recipient,
            fanout_id,
            topic,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct OpenOptions {
    pub config_path: Option<String>,
    pub sink: Option<String>,
}
#[pymethods]
impl OpenOptions {
    #[new]
    #[pyo3(signature = (config_path=None, sink=None))]
    fn new(config_path: Option<String>, sink: Option<String>) -> Self {
        Self { config_path, sink }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    pub agent: Option<String>,
    pub model: Option<String>,
    pub title: Option<String>,
    pub repo: Option<String>,
    pub git_ref: Option<String>,
    pub isolation: Option<IsolationKind>,
    pub fetch_remote: Option<bool>,
    pub template: Option<String>,
    pub setup: Option<String>,
    pub timeout_secs: Option<i32>,
    pub max_budget: Option<String>,
    pub unchecked: Option<bool>,
    pub tags: Option<Vec<String>>,
    pub labels: Option<String>,
}
#[pymethods]
impl DispatchSpec {
    #[new]
    #[pyo3(signature = (brief, env, agent=None, model=None, title=None, repo=None, git_ref=None, isolation=None, fetch_remote=None, template=None, setup=None, timeout_secs=None, max_budget=None, unchecked=None, tags=None, labels=None))]
    fn new(
        brief: String,
        env: String,
        agent: Option<String>,
        model: Option<String>,
        title: Option<String>,
        repo: Option<String>,
        git_ref: Option<String>,
        isolation: Option<IsolationKind>,
        fetch_remote: Option<bool>,
        template: Option<String>,
        setup: Option<String>,
        timeout_secs: Option<i32>,
        max_budget: Option<String>,
        unchecked: Option<bool>,
        tags: Option<Vec<String>>,
        labels: Option<String>,
    ) -> Self {
        Self {
            brief,
            env,
            agent,
            model,
            title,
            repo,
            git_ref,
            isolation,
            fetch_remote,
            template,
            setup,
            timeout_secs,
            max_budget,
            unchecked,
            tags,
            labels,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct SessionFilter {
    pub env: Option<String>,
    pub state: Option<SessionState>,
    pub dispatch_id: Option<String>,
}
#[pymethods]
impl SessionFilter {
    #[new]
    #[pyo3(signature = (env=None, state=None, dispatch_id=None))]
    fn new(env: Option<String>, state: Option<SessionState>, dispatch_id: Option<String>) -> Self {
        Self {
            env,
            state,
            dispatch_id,
        }
    }
}

/// An editor link into a session's working directory.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    pub url: Option<String>,
    pub detail: Option<String>,
}
#[pymethods]
impl WorkspaceLink {
    #[new]
    #[pyo3(signature = (session_uid, available, url=None, detail=None))]
    fn new(
        session_uid: String,
        available: bool,
        url: Option<String>,
        detail: Option<String>,
    ) -> Self {
        Self {
            session_uid,
            available,
            url,
            detail,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct EventOptions {
    pub session_uid: Option<String>,
    pub after_idx: Option<i64>,
    pub kinds: Option<Vec<EventKind>>,
}
#[pymethods]
impl EventOptions {
    #[new]
    #[pyo3(signature = (session_uid=None, after_idx=None, kinds=None))]
    fn new(
        session_uid: Option<String>,
        after_idx: Option<i64>,
        kinds: Option<Vec<EventKind>>,
    ) -> Self {
        Self {
            session_uid,
            after_idx,
            kinds,
        }
    }
}

/// Where a Manager-sent message goes. A worker never fills this: the
/// worker-role server defaults recipient = its Manager, anchored to the bound
/// session (deferred to the MCP layer). A Manager sets exactly one destination.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct SendTarget {
    pub tags: Option<Vec<String>>,
    pub sessions: Option<Vec<String>>,
    pub user: Option<String>,
}
#[pymethods]
impl SendTarget {
    #[new]
    #[pyo3(signature = (tags=None, sessions=None, user=None))]
    fn new(tags: Option<Vec<String>>, sessions: Option<Vec<String>>, user: Option<String>) -> Self {
        Self {
            tags,
            sessions,
            user,
        }
    }
}

/// Filter for the `messages` read. Absent fields don't constrain.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct MessagesFilter {
    pub fanout_id: Option<String>,
    pub recipient: Option<Party>,
    pub session_uid: Option<String>,
    pub topic: Option<String>,
    pub latest_per_topic: Option<bool>,
}
#[pymethods]
impl MessagesFilter {
    #[new]
    #[pyo3(signature = (fanout_id=None, recipient=None, session_uid=None, topic=None, latest_per_topic=None))]
    fn new(
        fanout_id: Option<String>,
        recipient: Option<Party>,
        session_uid: Option<String>,
        topic: Option<String>,
        latest_per_topic: Option<bool>,
    ) -> Self {
        Self {
            fanout_id,
            recipient,
            session_uid,
            topic,
            latest_per_topic,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}
#[pymethods]
impl ReconcileReport {
    #[new]
    #[pyo3(signature = (adopted, confirmed, lost, torn_down))]
    fn new(adopted: i32, confirmed: i32, lost: i32, torn_down: i32) -> Self {
        Self {
            adopted,
            confirmed,
            lost,
            torn_down,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct McpOptions {
    pub transport: Option<String>,
    pub role: Option<McpRole>,
    pub max_depth: Option<i32>,
}
#[pymethods]
impl McpOptions {
    #[new]
    #[pyo3(signature = (transport=None, role=None, max_depth=None))]
    fn new(transport: Option<String>, role: Option<McpRole>, max_depth: Option<i32>) -> Self {
        Self {
            transport,
            role,
            max_depth,
        }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct DriverPlanOptions {
    pub dialect: Option<String>,
    pub tables: Option<Vec<String>>,
}
#[pymethods]
impl DriverPlanOptions {
    #[new]
    #[pyo3(signature = (dialect=None, tables=None))]
    fn new(dialect: Option<String>, tables: Option<Vec<String>>) -> Self {
        Self { dialect, tables }
    }
}

#[pyclass(get_all)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
}
#[pymethods]
impl Statement {
    #[new]
    #[pyo3(signature = (sql, params))]
    fn new(sql: String, params: String) -> Self {
        Self { sql, params }
    }
}

/// What an environment can do: one row per (env, capability) the catalog
/// advertises. Mirrors the env_capabilities edge as a flat, returnable value
/// struct (the closed CapabilityKind vocabulary, plus open detail).
#[pyclass(get_all)]
#[derive(Clone)]
pub struct EnvCapability {
    pub env_slug: String,
    pub capability: CapabilityKind,
    pub detail: Option<String>,
}
#[pymethods]
impl EnvCapability {
    #[new]
    #[pyo3(signature = (env_slug, capability, detail=None))]
    fn new(env_slug: String, capability: CapabilityKind, detail: Option<String>) -> Self {
        Self {
            env_slug,
            capability,
            detail,
        }
    }
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Environment {
    pub slug: String,
    pub kind: EnvKind,
    pub display_name: Option<String>,
    pub endpoint: Option<String>,
    pub last_probed_at: Option<String>,
}
#[pymethods]
impl Environment {
    #[new]
    #[pyo3(signature = (slug, kind, display_name=None, endpoint=None, last_probed_at=None))]
    fn new(
        slug: String,
        kind: EnvKind,
        display_name: Option<String>,
        endpoint: Option<String>,
        last_probed_at: Option<String>,
    ) -> Self {
        Self {
            slug,
            kind,
            display_name,
            endpoint,
            last_probed_at,
        }
    }
}

/// env × agent × model availability (from the shipped catalog + config).
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}
#[pymethods]
impl Offering {
    #[new]
    #[pyo3(signature = (env_slug, agent_name, model_id, is_default))]
    fn new(env_slug: String, agent_name: String, model_id: String, is_default: bool) -> Self {
        Self {
            env_slug,
            agent_name,
            model_id,
            is_default,
        }
    }
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: SessionState,
    pub env_handle: Option<String>,
    pub url: Option<String>,
    pub resumed_from: Option<String>,
    pub started_at: Option<String>,
    pub ended_at: Option<String>,
    pub exit_reason: Option<ExitReason>,
    pub exit_detail: Option<String>,
    pub reaped_at: Option<String>,
}
#[pymethods]
impl Session {
    #[new]
    #[pyo3(signature = (uid, dispatch_id, state, env_handle=None, url=None, resumed_from=None, started_at=None, ended_at=None, exit_reason=None, exit_detail=None, reaped_at=None))]
    fn new(
        uid: String,
        dispatch_id: String,
        state: SessionState,
        env_handle: Option<String>,
        url: Option<String>,
        resumed_from: Option<String>,
        started_at: Option<String>,
        ended_at: Option<String>,
        exit_reason: Option<ExitReason>,
        exit_detail: Option<String>,
        reaped_at: Option<String>,
    ) -> Self {
        Self {
            uid,
            dispatch_id,
            state,
            env_handle,
            url,
            resumed_from,
            started_at,
            ended_at,
            exit_reason,
            exit_detail,
            reaped_at,
        }
    }
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: EventKind,
    pub fidelity: Fidelity,
    pub payload: String,
}
#[pymethods]
impl Event {
    #[new]
    #[pyo3(signature = (session_uid, idx, ts, kind, fidelity, payload))]
    fn new(
        session_uid: String,
        idx: i64,
        ts: String,
        kind: EventKind,
        fidelity: Fidelity,
        payload: String,
    ) -> Self {
        Self {
            session_uid,
            idx,
            ts,
            kind,
            fidelity,
            payload,
        }
    }
}

/// One message dropped in one inbox — the manager↔worker communication
/// primitive (notes/manager-worker-comms.md). The Manager mints these addressed
/// to a worker or the user; a worker mints them addressed (implicitly) to its
/// Manager. Disponent owns these rows — no environment backs them, so reconcile
/// skips them and durability is the SQLite mirror (design §11).
#[pyclass(get_all)]
#[derive(Clone)]
pub struct Message {
    pub id: String,
    pub created_at: String,
    pub sender: Party,
    pub recipient: Party,
    pub session_uid: String,
    pub body: String,
    pub in_reply_to: Option<String>,
    pub fanout_id: String,
    pub topic: Option<String>,
    pub acked_at: Option<String>,
}
#[pymethods]
impl Message {
    #[new]
    #[pyo3(signature = (id, created_at, sender, recipient, session_uid, body, fanout_id, in_reply_to=None, topic=None, acked_at=None))]
    fn new(
        id: String,
        created_at: String,
        sender: Party,
        recipient: Party,
        session_uid: String,
        body: String,
        fanout_id: String,
        in_reply_to: Option<String>,
        topic: Option<String>,
        acked_at: Option<String>,
    ) -> Self {
        Self {
            id,
            created_at,
            sender,
            recipient,
            session_uid,
            body,
            fanout_id,
            in_reply_to,
            topic,
            acked_at,
        }
    }
}

/// The `Disponent` contract — implement over the engine in `crate::core_impl`.
pub trait DisponentCore: Sized + Send + Sync + 'static {
    fn open(options: Option<OpenOptions>) -> anyhow::Result<Self>;
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn capabilities(&self) -> anyhow::Result<Vec<EnvCapability>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    fn events(&self, options: Option<EventOptions>) -> anyhow::Result<Box<dyn PollStream<Event>>>;
    fn send(
        &self,
        body: String,
        to: Option<SendTarget>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> anyhow::Result<Vec<Message>>;
    fn ack(&self, message_id: String) -> anyhow::Result<()>;
    fn messages(&self, filter: Option<MessagesFilter>) -> anyhow::Result<Vec<Message>>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
}

/// Poll-based stream from `Disponent.events`, dressed as a Python iterator.
#[pyclass]
pub struct Events {
    stream: Box<dyn PollStream<Event>>,
}
#[pymethods]
impl Events {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }
    fn __next__(&self, py: Python<'_>) -> Option<Event> {
        py.detach(|| loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // None => StopIteration
            }
        })
    }
}

/// Poll-based stream from `Disponent.driverPlan`, dressed as a Python iterator.
#[pyclass]
pub struct DriverPlan {
    stream: Box<dyn PollStream<Statement>>,
}
#[pymethods]
impl DriverPlan {
    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }
    fn __next__(&self, py: Python<'_>) -> Option<Statement> {
        py.detach(|| loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Some(v),
                Poll::Idle => continue,
                Poll::Closed => return None, // None => StopIteration
            }
        })
    }
}

#[pyclass]
pub struct Disponent {
    // pub(crate): @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::DisponentImpl>,
}

#[pymethods]
impl Disponent {
    #[new]
    #[pyo3(signature = (config_path=None, sink=None))]
    fn new(config_path: Option<String>, sink: Option<String>) -> PyResult<Self> {
        let open_options_arg = OpenOptions { config_path, sink };

        Ok(Self {
            core: Arc::new(
                <crate::core_impl::DisponentImpl as DisponentCore>::open(Some(open_options_arg))
                    .map_err(err)?,
            ),
        })
    }
    #[pyo3(signature = ())]
    fn environments(&self, py: Python<'_>) -> PyResult<Vec<Environment>> {
        let core = self.core.clone();
        py.detach(move || core.environments()).map_err(err)
    }
    #[pyo3(signature = (env_slug=None))]
    fn refresh(&self, py: Python<'_>, env_slug: Option<String>) -> PyResult<Vec<Environment>> {
        let core = self.core.clone();
        py.detach(move || core.refresh(env_slug)).map_err(err)
    }
    /// The offerings table: every env × agent × model the catalog knows, each
    /// flagged `isDefault` when it's the pick for a dispatch that names only the
    /// environment. Lets a consumer enumerate what can run where without reaching
    /// for the raw driver plan.
    #[pyo3(signature = ())]
    fn offerings(&self, py: Python<'_>) -> PyResult<Vec<Offering>> {
        let core = self.core.clone();
        py.detach(move || core.offerings()).map_err(err)
    }
    /// Per-env capabilities: what each environment can do, one row per
    /// (env, capability) the catalog advertises. Lets a consumer grade backends
    /// by what they support without reaching for the raw driver plan.
    #[pyo3(signature = ())]
    fn capabilities(&self, py: Python<'_>) -> PyResult<Vec<EnvCapability>> {
        let core = self.core.clone();
        py.detach(move || core.capabilities()).map_err(err)
    }
    #[pyo3(signature = (brief, env, agent=None, model=None, title=None, repo=None, git_ref=None, isolation=None, fetch_remote=None, template=None, setup=None, timeout_secs=None, max_budget=None, unchecked=None, tags=None, labels=None))]
    fn dispatch(
        &self,
        py: Python<'_>,
        brief: String,
        env: String,
        agent: Option<String>,
        model: Option<String>,
        title: Option<String>,
        repo: Option<String>,
        git_ref: Option<String>,
        isolation: Option<IsolationKind>,
        fetch_remote: Option<bool>,
        template: Option<String>,
        setup: Option<String>,
        timeout_secs: Option<i32>,
        max_budget: Option<String>,
        unchecked: Option<bool>,
        tags: Option<Vec<String>>,
        labels: Option<String>,
    ) -> PyResult<Session> {
        let dispatch_spec_arg = DispatchSpec {
            brief,
            env,
            agent,
            model,
            title,
            repo,
            git_ref,
            isolation,
            fetch_remote,
            template,
            setup,
            timeout_secs,
            max_budget,
            unchecked,
            tags,
            labels,
        };

        let core = self.core.clone();
        py.detach(move || core.dispatch(dispatch_spec_arg))
            .map_err(err)
    }
    #[pyo3(signature = (uid))]
    fn session(&self, py: Python<'_>, uid: String) -> PyResult<Option<Session>> {
        let core = self.core.clone();
        py.detach(move || core.session(uid)).map_err(err)
    }
    #[pyo3(signature = (env=None, state=None, dispatch_id=None))]
    fn sessions(
        &self,
        py: Python<'_>,
        env: Option<String>,
        state: Option<SessionState>,
        dispatch_id: Option<String>,
    ) -> PyResult<Vec<Session>> {
        let session_filter_arg = SessionFilter {
            env,
            state,
            dispatch_id,
        };

        let core = self.core.clone();
        py.detach(move || core.sessions(Some(session_filter_arg)))
            .map_err(err)
    }
    /// Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.
    #[pyo3(signature = (session_uid))]
    fn workspace_link(&self, py: Python<'_>, session_uid: String) -> PyResult<WorkspaceLink> {
        let core = self.core.clone();
        py.detach(move || core.workspace_link(session_uid))
            .map_err(err)
    }
    #[pyo3(signature = (session_uid=None, after_idx=None, kinds=None))]
    fn events(
        &self,
        session_uid: Option<String>,
        after_idx: Option<i64>,
        kinds: Option<Vec<EventKind>>,
    ) -> PyResult<Events> {
        let event_options_arg = EventOptions {
            session_uid,
            after_idx,
            kinds,
        };

        Ok(Events {
            stream: self.core.events(Some(event_options_arg)).map_err(err)?,
        })
    }
    /// The one messaging primitive (notes/manager-worker-comms.md §6). A Manager
    /// `to` names a tagged worker subset (fan-out) or the user; recipients resolve
    /// at send time to a concrete list (a snapshot, never kept live). One Message
    /// is minted per matched session, all sharing a freshly minted `fanoutId`;
    /// `topic` (optional) is the supersession key for latest-wins (§7). Returns the
    /// Messages minted. Delivery is the reader's `events` pull; a message to a
    /// concrete live worker is also delivered best-effort to its prompt on an
    /// interact-capable env (the legacy `send` behavior, now one backend delivery).
    /// Worker self-send (recipient forced to the Manager) is a worker-role MCP
    /// concern, deferred — the core send is the Manager surface.
    #[pyo3(signature = (body, tags=None, sessions=None, user=None, in_reply_to=None, topic=None))]
    fn send(
        &self,
        py: Python<'_>,
        body: String,
        tags: Option<Vec<String>>,
        sessions: Option<Vec<String>>,
        user: Option<String>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> PyResult<Vec<Message>> {
        let send_target_arg = SendTarget {
            tags,
            sessions,
            user,
        };

        let core = self.core.clone();
        py.detach(move || core.send(body, Some(send_target_arg), in_reply_to, topic))
            .map_err(err)
    }
    /// Acknowledge a message you received (received/handled): stamps `ackedAt`,
    /// which the Manager observes across a `fanoutId` to see "N of M acted" (§7).
    /// Idempotent.
    #[pyo3(signature = (message_id))]
    fn ack(&self, py: Python<'_>, message_id: String) -> PyResult<()> {
        let core = self.core.clone();
        py.detach(move || core.ack(message_id)).map_err(err)
    }
    /// Read Messages, filtered. The Manager's fan-out ack-progress view
    /// (`{fanoutId}`) and a recipient's inbox (`{recipient, sessionUid}`, optionally
    /// `latestPerTopic` for the read-side latest-wins collapse, §7).
    #[pyo3(signature = (fanout_id=None, recipient=None, session_uid=None, topic=None, latest_per_topic=None))]
    fn messages(
        &self,
        py: Python<'_>,
        fanout_id: Option<String>,
        recipient: Option<Party>,
        session_uid: Option<String>,
        topic: Option<String>,
        latest_per_topic: Option<bool>,
    ) -> PyResult<Vec<Message>> {
        let messages_filter_arg = MessagesFilter {
            fanout_id,
            recipient,
            session_uid,
            topic,
            latest_per_topic,
        };

        let core = self.core.clone();
        py.detach(move || core.messages(Some(messages_filter_arg)))
            .map_err(err)
    }
    #[pyo3(signature = (session_uid))]
    fn cancel(&self, py: Python<'_>, session_uid: String) -> PyResult<Session> {
        let core = self.core.clone();
        py.detach(move || core.cancel(session_uid)).map_err(err)
    }
    #[pyo3(signature = (session_uid))]
    fn resume(&self, py: Python<'_>, session_uid: String) -> PyResult<Session> {
        let core = self.core.clone();
        py.detach(move || core.resume(session_uid)).map_err(err)
    }
    #[pyo3(signature = (session_uid))]
    fn reap(&self, py: Python<'_>, session_uid: String) -> PyResult<Session> {
        let core = self.core.clone();
        py.detach(move || core.reap(session_uid)).map_err(err)
    }
    #[pyo3(signature = ())]
    fn reconcile(&self, py: Python<'_>) -> PyResult<ReconcileReport> {
        let core = self.core.clone();
        py.detach(move || core.reconcile()).map_err(err)
    }
    #[pyo3(signature = (dialect=None, tables=None))]
    fn driver_plan(
        &self,
        dialect: Option<String>,
        tables: Option<Vec<String>>,
    ) -> PyResult<DriverPlan> {
        let driver_plan_options_arg = DriverPlanOptions { dialect, tables };

        Ok(DriverPlan {
            stream: self
                .core
                .driver_plan(Some(driver_plan_options_arg))
                .map_err(err)?,
        })
    }
    // @manual: wait — hand-written in lib.rs if this binding offers it.
    // @manual: serveMcp — hand-written in lib.rs if this binding offers it.
}

/// Register every generated class + function on the `#[pymodule]`.
pub(crate) fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<EnvKind>()?;
    m.add_class::<SessionState>()?;
    m.add_class::<ExitReason>()?;
    m.add_class::<IsolationKind>()?;
    m.add_class::<TemplateKind>()?;
    m.add_class::<CapabilityKind>()?;
    m.add_class::<EventKind>()?;
    m.add_class::<Party>()?;
    m.add_class::<Fidelity>()?;
    m.add_class::<ArtifactKind>()?;
    m.add_class::<McpRole>()?;
    m.add_class::<StateChange>()?;
    m.add_class::<AgentMessage>()?;
    m.add_class::<ToolCallInfo>()?;
    m.add_class::<ToolResultInfo>()?;
    m.add_class::<LogLine>()?;
    m.add_class::<UsageDelta>()?;
    m.add_class::<ArtifactRef>()?;
    m.add_class::<RawObservation>()?;
    m.add_class::<MailRef>()?;
    m.add_class::<OpenOptions>()?;
    m.add_class::<DispatchSpec>()?;
    m.add_class::<SessionFilter>()?;
    m.add_class::<WorkspaceLink>()?;
    m.add_class::<EventOptions>()?;
    m.add_class::<SendTarget>()?;
    m.add_class::<MessagesFilter>()?;
    m.add_class::<ReconcileReport>()?;
    m.add_class::<McpOptions>()?;
    m.add_class::<DriverPlanOptions>()?;
    m.add_class::<Statement>()?;
    m.add_class::<EnvCapability>()?;
    m.add_class::<Environment>()?;
    m.add_class::<Offering>()?;
    m.add_class::<Session>()?;
    m.add_class::<Event>()?;
    m.add_class::<Message>()?;
    m.add_class::<Events>()?;
    m.add_class::<DriverPlan>()?;
    m.add_class::<Disponent>()?;
    Ok(())
}
