//! GENERATED by fluessig bindgen from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::{AsyncGenerator, AsyncTask, Result};
use napi::{Env, Task};
use napi_derive::napi;
use std::future::Future;
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum EnvKind {
    #[napi(value = "local")]
    Local,
    #[napi(value = "exe_dev")]
    ExeDev,
    #[napi(value = "modal")]
    Modal,
    #[napi(value = "claude_code_web")]
    ClaudeCodeWeb,
    #[napi(value = "custom")]
    Custom,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum SessionState {
    #[napi(value = "queued")]
    Queued,
    #[napi(value = "provisioning")]
    Provisioning,
    #[napi(value = "running")]
    Running,
    #[napi(value = "needs_input")]
    NeedsInput,
    #[napi(value = "completed")]
    Completed,
    #[napi(value = "failed")]
    Failed,
    #[napi(value = "cancelled")]
    Cancelled,
    #[napi(value = "lost")]
    Lost,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum ExitReason {
    #[napi(value = "ok")]
    Ok,
    #[napi(value = "error")]
    Error,
    #[napi(value = "signal")]
    Signal,
    #[napi(value = "timeout")]
    Timeout,
    #[napi(value = "budget")]
    Budget,
    #[napi(value = "setup")]
    Setup,
    #[napi(value = "unknown")]
    Unknown,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum IsolationKind {
    #[napi(value = "none")]
    None,
    #[napi(value = "worktree")]
    Worktree,
    #[napi(value = "container")]
    Container,
    #[napi(value = "vm")]
    Vm,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum TemplateKind {
    #[napi(value = "vm_image")]
    VmImage,
    #[napi(value = "container_image")]
    ContainerImage,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum CapabilityKind {
    #[napi(value = "dispatch")]
    Dispatch,
    #[napi(value = "interact")]
    Interact,
    #[napi(value = "observe_stream")]
    ObserveStream,
    #[napi(value = "observe_poll")]
    ObservePoll,
    #[napi(value = "list_sessions")]
    ListSessions,
    #[napi(value = "resume")]
    Resume,
    #[napi(value = "cancel")]
    Cancel,
    #[napi(value = "teardown")]
    Teardown,
    #[napi(value = "isolation_worktree")]
    IsolationWorktree,
    #[napi(value = "isolation_container")]
    IsolationContainer,
    #[napi(value = "isolation_vm")]
    IsolationVm,
    #[napi(value = "templates")]
    Templates,
    #[napi(value = "artifact_fetch")]
    ArtifactFetch,
    #[napi(value = "usage_report")]
    UsageReport,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum EventKind {
    #[napi(value = "state")]
    State,
    #[napi(value = "message")]
    Message,
    #[napi(value = "tool_call")]
    ToolCall,
    #[napi(value = "tool_result")]
    ToolResult,
    #[napi(value = "log")]
    Log,
    #[napi(value = "usage")]
    Usage,
    #[napi(value = "artifact")]
    Artifact,
    #[napi(value = "raw")]
    Raw,
    #[napi(value = "mail")]
    Mail,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum Party {
    #[napi(value = "manager")]
    Manager,
    #[napi(value = "worker")]
    Worker,
    #[napi(value = "user")]
    User,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum Fidelity {
    #[napi(value = "exact")]
    Exact,
    #[napi(value = "derived")]
    Derived,
    #[napi(value = "scraped")]
    Scraped,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum ArtifactKind {
    #[napi(value = "branch")]
    Branch,
    #[napi(value = "pull_request")]
    PullRequest,
    #[napi(value = "patch")]
    Patch,
    #[napi(value = "file")]
    File,
    #[napi(value = "report")]
    Report,
    #[napi(value = "url")]
    Url,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum McpRole {
    #[napi(value = "supervisor")]
    Supervisor,
    #[napi(value = "worker")]
    Worker,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum AttachTransport {
    #[napi(value = "tmux")]
    Tmux,
    #[napi(value = "dsp_hold")]
    DspHold,
    #[napi(value = "ttyd")]
    Ttyd,
}

#[napi(object)]
#[derive(Clone)]
pub struct StateChange {
    pub from: SessionState,
    pub to: SessionState,
}

#[napi(object)]
#[derive(Clone)]
pub struct AgentMessage {
    pub role: String,
    pub text: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct ToolCallInfo {
    pub tool: String,
    pub input: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ToolResultInfo {
    pub tool: String,
    pub ok: bool,
    pub output: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct LogLine {
    pub line: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct UsageDelta {
    pub model_id: Option<String>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub cost_cents: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ArtifactRef {
    pub artifact_idx: i64,
}

#[napi(object)]
#[derive(Clone)]
pub struct RawObservation {
    pub source: String,
    pub data: String,
}

/// Pointer + the fields a reader needs to triage a `mail` event without
/// fetching the Message: direction (sender/recipient), the fan-out it belongs
/// to, and its topic (so a reader can group by topic for latest-wins).
#[napi(object)]
#[derive(Clone)]
pub struct MailRef {
    pub message_id: String,
    pub sender: Party,
    pub recipient: Party,
    pub fanout_id: String,
    pub topic: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct OpenOptions {
    pub config_path: Option<String>,
    pub sink: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    pub agent: Option<String>,
    pub model: Option<String>,
    pub title: Option<String>,
    pub repo: Option<String>,
    pub git_ref: Option<String>,
    pub isolation: Option<IsolationKind>,
    pub fetch_remote: Option<bool>,
    pub template: Option<String>,
    pub setup: Option<String>,
    pub timeout_secs: Option<i32>,
    pub max_budget: Option<String>,
    pub unchecked: Option<bool>,
    pub tags: Option<Vec<String>>,
    pub labels: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct SessionFilter {
    pub env: Option<String>,
    pub state: Option<SessionState>,
    pub dispatch_id: Option<String>,
}

/// An editor link into a session's working directory.
#[napi(object)]
#[derive(Clone)]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    pub url: Option<String>,
    pub detail: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct EventOptions {
    pub session_uid: Option<String>,
    pub after_idx: Option<i64>,
    pub kinds: Option<Vec<EventKind>>,
}

/// Where a Manager-sent message goes. A worker never fills this: the
/// worker-role server defaults recipient = its Manager, anchored to the bound
/// session (deferred to the MCP layer). A Manager sets exactly one destination.
#[napi(object)]
#[derive(Clone)]
pub struct SendTarget {
    pub tags: Option<Vec<String>>,
    pub sessions: Option<Vec<String>>,
    pub user: Option<String>,
}

/// Filter for the `messages` read. Absent fields don't constrain.
#[napi(object)]
#[derive(Clone)]
pub struct MessagesFilter {
    pub fanout_id: Option<String>,
    pub recipient: Option<Party>,
    pub session_uid: Option<String>,
    pub topic: Option<String>,
    pub latest_per_topic: Option<bool>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}

#[napi(object)]
#[derive(Clone)]
pub struct McpOptions {
    pub transport: Option<String>,
    pub role: Option<McpRole>,
    pub max_depth: Option<i32>,
}

#[napi(object)]
#[derive(Clone)]
pub struct DriverPlanOptions {
    pub dialect: Option<String>,
    pub tables: Option<Vec<String>>,
}

#[napi(object)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
}

/// What an environment can do: one row per (env, capability) the catalog
/// advertises. Mirrors the env_capabilities edge as a flat, returnable value
/// struct (the closed CapabilityKind vocabulary, plus open detail).
#[napi(object)]
#[derive(Clone)]
pub struct EnvCapability {
    pub env_slug: String,
    pub capability: CapabilityKind,
    pub detail: Option<String>,
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[napi(object)]
#[derive(Clone)]
pub struct Environment {
    pub slug: String,
    pub kind: EnvKind,
    pub display_name: Option<String>,
    pub endpoint: Option<String>,
    pub last_probed_at: Option<String>,
}

/// env × agent × model availability (from the shipped catalog + config).
#[napi(object)]
#[derive(Clone)]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[napi(object)]
#[derive(Clone)]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: SessionState,
    pub env_handle: Option<String>,
    pub attach_transport: Option<AttachTransport>,
    pub attach_endpoint: Option<String>,
    pub attach_target: Option<String>,
    pub attach_url: Option<String>,
    pub url: Option<String>,
    pub resumed_from: Option<String>,
    pub started_at: Option<String>,
    pub ended_at: Option<String>,
    pub exit_reason: Option<ExitReason>,
    pub exit_detail: Option<String>,
    pub reaped_at: Option<String>,
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[napi(object)]
#[derive(Clone)]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: EventKind,
    pub fidelity: Fidelity,
    pub payload: String,
}

/// One message dropped in one inbox — the manager↔worker communication
/// primitive (notes/manager-worker-comms.md). The Manager mints these addressed
/// to a worker or the user; a worker mints them addressed (implicitly) to its
/// Manager. Disponent owns these rows — no environment backs them, so reconcile
/// skips them and durability is the SQLite mirror (design §11).
#[napi(object)]
#[derive(Clone)]
pub struct Message {
    pub id: String,
    pub created_at: String,
    pub sender: Party,
    pub recipient: Party,
    pub session_uid: String,
    pub body: String,
    pub in_reply_to: Option<String>,
    pub fanout_id: String,
    pub topic: Option<String>,
    pub acked_at: Option<String>,
}

/// The `Disponent` contract — implement over the engine in `crate::core_impl`.
pub trait DisponentCore: Sized + Send + Sync + 'static {
    fn open(options: Option<OpenOptions>) -> anyhow::Result<Self>;
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn capabilities(&self) -> anyhow::Result<Vec<EnvCapability>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    fn events(&self, options: Option<EventOptions>) -> anyhow::Result<Box<dyn PollStream<Event>>>;
    fn send(
        &self,
        body: String,
        to: Option<SendTarget>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> anyhow::Result<Vec<Message>>;
    fn ack(&self, message_id: String) -> anyhow::Result<()>;
    fn messages(&self, filter: Option<MessagesFilter>) -> anyhow::Result<Vec<Message>>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
}

/// Event stream from `Disponent.events`.
///
/// Primary surface: a JS async-iterable — `for await (const ev of stream)`.
/// Retained surface: `next()` poll cursor (resolves `null` at end) for
/// consumers that cannot use async iteration or napi's `tokio_rt` feature.
///
/// DEFAULT error model = idiomatic native-TS REJECT: a mid-stream core
/// failure (`Poll::Failed`) maps to `Err(err(e))`, so the awaited pull
/// REJECTS and the `for await` loop THROWS — safe by default, never a
/// silent-swallow. Annotate the op `@streamError` to opt into the
/// error-AS-EVENT model instead (mirror a source library like pi).
#[napi(async_iterator)]
pub struct Events {
    stream: Arc<dyn PollStream<Event>>,
}

// Async-iterable surface (Symbol.asyncIterator). napi drives one pull at a
// time, so backpressure is one in-flight poll by construction.
#[napi]
impl AsyncGenerator for Events {
    type Yield = Event;
    type Next = ();
    type Return = ();

    fn next(
        &mut self,
        _value: Option<Self::Next>,
    ) -> impl Future<Output = Result<Option<Self::Yield>>> + Send + 'static {
        let stream = self.stream.clone();
        async move {
            loop {
                let s = stream.clone();
                // Drive the blocking poll off the async runtime so the Node
                // event loop is never blocked.
                let poll =
                    napi::tokio::task::spawn_blocking(move || s.poll(Duration::from_millis(500)))
                        .await
                        .map_err(err)?;
                // DEFAULT throw-mode: a mid-stream failure REJECTS the pull
                // (native TS — the `for await` loop throws). Opt into
                // error-as-event with `@streamError`.
                match poll {
                    Poll::Item(v) => return Ok(Some(v)),
                    Poll::Idle => continue,
                    Poll::Closed => return Ok(None),
                    Poll::Failed(e) => return Err(err(e)),
                }
            }
        }
    }

    fn complete(
        &mut self,
        _value: Option<Self::Return>,
    ) -> impl Future<Output = Result<Option<Self::Yield>>> + Send + 'static {
        // Cancellation: consumer called `return()` (e.g. `break` in for-await).
        let stream = self.stream.clone();
        async move {
            stream.close();
            Ok(None)
        }
    }
}

// Backstop: guarantee core-side close even if the consumer neither
// exhausts nor cancels the iterator.
impl Drop for Events {
    fn drop(&mut self) {
        self.stream.close();
    }
}

// Retained poll cursor: `next(): Promise<Item | null>`.
pub struct NextEventsTask {
    stream: Arc<dyn PollStream<Event>>,
}
impl Task for NextEventsTask {
    type Output = Option<Event>;
    type JsValue = Option<Event>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
                // throw-mode: reject the pull (native TS).
                Poll::Failed(e) => return Err(err(e)),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl Events {
    #[napi(ts_return_type = "Promise<Event | null>")]
    pub fn next(&self) -> AsyncTask<NextEventsTask> {
        AsyncTask::new(NextEventsTask {
            stream: self.stream.clone(),
        })
    }
}

/// Event stream from `Disponent.driverPlan`.
///
/// Primary surface: a JS async-iterable — `for await (const ev of stream)`.
/// Retained surface: `next()` poll cursor (resolves `null` at end) for
/// consumers that cannot use async iteration or napi's `tokio_rt` feature.
///
/// DEFAULT error model = idiomatic native-TS REJECT: a mid-stream core
/// failure (`Poll::Failed`) maps to `Err(err(e))`, so the awaited pull
/// REJECTS and the `for await` loop THROWS — safe by default, never a
/// silent-swallow. Annotate the op `@streamError` to opt into the
/// error-AS-EVENT model instead (mirror a source library like pi).
#[napi(async_iterator)]
pub struct DriverPlan {
    stream: Arc<dyn PollStream<Statement>>,
}

// Async-iterable surface (Symbol.asyncIterator). napi drives one pull at a
// time, so backpressure is one in-flight poll by construction.
#[napi]
impl AsyncGenerator for DriverPlan {
    type Yield = Statement;
    type Next = ();
    type Return = ();

    fn next(
        &mut self,
        _value: Option<Self::Next>,
    ) -> impl Future<Output = Result<Option<Self::Yield>>> + Send + 'static {
        let stream = self.stream.clone();
        async move {
            loop {
                let s = stream.clone();
                // Drive the blocking poll off the async runtime so the Node
                // event loop is never blocked.
                let poll =
                    napi::tokio::task::spawn_blocking(move || s.poll(Duration::from_millis(500)))
                        .await
                        .map_err(err)?;
                // DEFAULT throw-mode: a mid-stream failure REJECTS the pull
                // (native TS — the `for await` loop throws). Opt into
                // error-as-event with `@streamError`.
                match poll {
                    Poll::Item(v) => return Ok(Some(v)),
                    Poll::Idle => continue,
                    Poll::Closed => return Ok(None),
                    Poll::Failed(e) => return Err(err(e)),
                }
            }
        }
    }

    fn complete(
        &mut self,
        _value: Option<Self::Return>,
    ) -> impl Future<Output = Result<Option<Self::Yield>>> + Send + 'static {
        // Cancellation: consumer called `return()` (e.g. `break` in for-await).
        let stream = self.stream.clone();
        async move {
            stream.close();
            Ok(None)
        }
    }
}

// Backstop: guarantee core-side close even if the consumer neither
// exhausts nor cancels the iterator.
impl Drop for DriverPlan {
    fn drop(&mut self) {
        self.stream.close();
    }
}

// Retained poll cursor: `next(): Promise<Item | null>`.
pub struct NextDriverPlanTask {
    stream: Arc<dyn PollStream<Statement>>,
}
impl Task for NextDriverPlanTask {
    type Output = Option<Statement>;
    type JsValue = Option<Statement>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
                // throw-mode: reject the pull (native TS).
                Poll::Failed(e) => return Err(err(e)),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl DriverPlan {
    #[napi(ts_return_type = "Promise<Statement | null>")]
    pub fn next(&self) -> AsyncTask<NextDriverPlanTask> {
        AsyncTask::new(NextDriverPlanTask {
            stream: self.stream.clone(),
        })
    }
}

pub struct EnvironmentsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for EnvironmentsTask {
    type Output = Vec<Environment>;
    type JsValue = Vec<Environment>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.environments().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct RefreshTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    env_slug: Option<String>,
}
impl Task for RefreshTask {
    type Output = Vec<Environment>;
    type JsValue = Vec<Environment>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.refresh(self.env_slug.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct OfferingsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for OfferingsTask {
    type Output = Vec<Offering>;
    type JsValue = Vec<Offering>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.offerings().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CapabilitiesTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for CapabilitiesTask {
    type Output = Vec<EnvCapability>;
    type JsValue = Vec<EnvCapability>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.capabilities().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct DispatchTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    spec: DispatchSpec,
}
impl Task for DispatchTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.dispatch(self.spec.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SessionTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    uid: String,
}
impl Task for SessionTask {
    type Output = Option<Session>;
    type JsValue = Option<Session>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.session(self.uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SessionsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    filter: Option<SessionFilter>,
}
impl Task for SessionsTask {
    type Output = Vec<Session>;
    type JsValue = Vec<Session>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.sessions(self.filter.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct WorkspaceLinkTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for WorkspaceLinkTask {
    type Output = WorkspaceLink;
    type JsValue = WorkspaceLink;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core
            .workspace_link(self.session_uid.clone())
            .map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SendTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    body: String,
    to: Option<SendTarget>,
    in_reply_to: Option<String>,
    topic: Option<String>,
}
impl Task for SendTask {
    type Output = Vec<Message>;
    type JsValue = Vec<Message>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core
            .send(
                self.body.clone(),
                self.to.clone(),
                self.in_reply_to.clone(),
                self.topic.clone(),
            )
            .map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct AckTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    message_id: String,
}
impl Task for AckTask {
    type Output = ();
    type JsValue = ();
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.ack(self.message_id.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct MessagesTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    filter: Option<MessagesFilter>,
}
impl Task for MessagesTask {
    type Output = Vec<Message>;
    type JsValue = Vec<Message>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.messages(self.filter.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CancelTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for CancelTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.cancel(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ResumeTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for ResumeTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.resume(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ReapTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for ReapTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.reap(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ReconcileTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for ReconcileTask {
    type Output = ReconcileReport;
    type JsValue = ReconcileReport;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.reconcile().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

#[napi]
pub struct Disponent {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::DisponentImpl>,
}

#[napi]
impl Disponent {
    #[napi(constructor)]
    pub fn new(options: Option<OpenOptions>) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::DisponentImpl as DisponentCore>::open(options).map_err(err)?,
            ),
        })
    }
    #[napi(ts_return_type = "Promise<Environment[]>")]
    pub fn environments(&self) -> AsyncTask<EnvironmentsTask> {
        AsyncTask::new(EnvironmentsTask {
            core: self.core.clone(),
        })
    }
    #[napi(ts_return_type = "Promise<Environment[]>")]
    pub fn refresh(&self, env_slug: Option<String>) -> AsyncTask<RefreshTask> {
        AsyncTask::new(RefreshTask {
            core: self.core.clone(),
            env_slug,
        })
    }
    /// The offerings table: every env × agent × model the catalog knows, each
    /// flagged `isDefault` when it's the pick for a dispatch that names only the
    /// environment. Lets a consumer enumerate what can run where without reaching
    /// for the raw driver plan.
    #[napi(ts_return_type = "Promise<Offering[]>")]
    pub fn offerings(&self) -> AsyncTask<OfferingsTask> {
        AsyncTask::new(OfferingsTask {
            core: self.core.clone(),
        })
    }
    /// Per-env capabilities: what each environment can do, one row per
    /// (env, capability) the catalog advertises. Lets a consumer grade backends
    /// by what they support without reaching for the raw driver plan.
    #[napi(ts_return_type = "Promise<EnvCapability[]>")]
    pub fn capabilities(&self) -> AsyncTask<CapabilitiesTask> {
        AsyncTask::new(CapabilitiesTask {
            core: self.core.clone(),
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn dispatch(&self, spec: DispatchSpec) -> AsyncTask<DispatchTask> {
        AsyncTask::new(DispatchTask {
            core: self.core.clone(),
            spec,
        })
    }
    #[napi(ts_return_type = "Promise<Session | null>")]
    pub fn session(&self, uid: String) -> AsyncTask<SessionTask> {
        AsyncTask::new(SessionTask {
            core: self.core.clone(),
            uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session[]>")]
    pub fn sessions(&self, filter: Option<SessionFilter>) -> AsyncTask<SessionsTask> {
        AsyncTask::new(SessionsTask {
            core: self.core.clone(),
            filter,
        })
    }
    /// Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.
    #[napi(ts_return_type = "Promise<WorkspaceLink>")]
    pub fn workspace_link(&self, session_uid: String) -> AsyncTask<WorkspaceLinkTask> {
        AsyncTask::new(WorkspaceLinkTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    // pre-start boundary: building the stream (setup/validation) always
    // THROWS on a core Err — independent of the stream's error model.
    #[napi]
    pub fn events(&self, options: Option<EventOptions>) -> Result<Events> {
        Ok(Events {
            stream: Arc::from(self.core.events(options).map_err(err)?),
        })
    }
    /// The one messaging primitive (notes/manager-worker-comms.md §6). A Manager
    /// `to` names a tagged worker subset (fan-out) or the user; recipients resolve
    /// at send time to a concrete list (a snapshot, never kept live). One Message
    /// is minted per matched session, all sharing a freshly minted `fanoutId`;
    /// `topic` (optional) is the supersession key for latest-wins (§7). Returns the
    /// Messages minted. Delivery is the reader's `events` pull; a message to a
    /// concrete live worker is also delivered best-effort to its prompt on an
    /// interact-capable env (the legacy `send` behavior, now one backend delivery).
    /// Worker self-send (recipient forced to the Manager) is a worker-role MCP
    /// concern, deferred — the core send is the Manager surface.
    ///
    /// `#[fluessig(worker)]`: safe on a worker-role MCP surface — it lowers to
    /// the `workerHint` annotation the gate widens on (notes/manager-worker-comms.md
    /// §5). A worker's `send` is recipient-forced to its Manager by the
    /// worker-role server; it can never address a sibling or the environment.
    #[napi(ts_return_type = "Promise<Message[]>")]
    pub fn send(
        &self,
        body: String,
        to: Option<SendTarget>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> AsyncTask<SendTask> {
        AsyncTask::new(SendTask {
            core: self.core.clone(),
            body,
            to,
            in_reply_to,
            topic,
        })
    }
    /// Acknowledge a message you received (received/handled): stamps `ackedAt`,
    /// which the Manager observes across a `fanoutId` to see "N of M acted" (§7).
    /// Idempotent.
    ///
    /// `#[fluessig(worker)]`: worker-surface safe (§5) — a worker acks only its
    /// own inbox, enforced by the worker-role server.
    #[napi(ts_return_type = "Promise<void>")]
    pub fn ack(&self, message_id: String) -> AsyncTask<AckTask> {
        AsyncTask::new(AckTask {
            core: self.core.clone(),
            message_id,
        })
    }
    /// Read Messages, filtered. The Manager's fan-out ack-progress view
    /// (`{fanoutId}`) and a recipient's inbox (`{recipient, sessionUid}`, optionally
    /// `latestPerTopic` for the read-side latest-wins collapse, §7).
    #[napi(ts_return_type = "Promise<Message[]>")]
    pub fn messages(&self, filter: Option<MessagesFilter>) -> AsyncTask<MessagesTask> {
        AsyncTask::new(MessagesTask {
            core: self.core.clone(),
            filter,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn cancel(&self, session_uid: String) -> AsyncTask<CancelTask> {
        AsyncTask::new(CancelTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn resume(&self, session_uid: String) -> AsyncTask<ResumeTask> {
        AsyncTask::new(ResumeTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn reap(&self, session_uid: String) -> AsyncTask<ReapTask> {
        AsyncTask::new(ReapTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<ReconcileReport>")]
    pub fn reconcile(&self) -> AsyncTask<ReconcileTask> {
        AsyncTask::new(ReconcileTask {
            core: self.core.clone(),
        })
    }
    // pre-start boundary: building the stream (setup/validation) always
    // THROWS on a core Err — independent of the stream's error model.
    #[napi]
    pub fn driver_plan(&self, options: Option<DriverPlanOptions>) -> Result<DriverPlan> {
        Ok(DriverPlan {
            stream: Arc::from(self.core.driver_plan(options).map_err(err)?),
        })
    }
    // @manual: wait — hand-written in lib.rs.
    // @manual: serveMcp — hand-written in lib.rs.
}
