//! GENERATED by fluessig bindgen from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::{AsyncTask, Result};
use napi::{Env, Task};
use napi_derive::napi;
use std::sync::Arc;
use std::time::Duration;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// One poll result from a core stream (the sync primitive every stream shape dresses).
pub enum Poll<T> {
    Item(T),
    Idle,
    Closed,
}

/// The one sync primitive: a blocking, timeout-bounded poll.
pub trait PollStream<T>: Send + Sync {
    fn poll(&self, timeout: Duration) -> Poll<T>;
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum EnvKind {
    #[napi(value = "local")]
    Local,
    #[napi(value = "exe_dev")]
    ExeDev,
    #[napi(value = "claude_code_web")]
    ClaudeCodeWeb,
    #[napi(value = "custom")]
    Custom,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum SessionState {
    #[napi(value = "queued")]
    Queued,
    #[napi(value = "provisioning")]
    Provisioning,
    #[napi(value = "running")]
    Running,
    #[napi(value = "needs_input")]
    NeedsInput,
    #[napi(value = "completed")]
    Completed,
    #[napi(value = "failed")]
    Failed,
    #[napi(value = "cancelled")]
    Cancelled,
    #[napi(value = "lost")]
    Lost,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum ExitReason {
    #[napi(value = "ok")]
    Ok,
    #[napi(value = "error")]
    Error,
    #[napi(value = "signal")]
    Signal,
    #[napi(value = "timeout")]
    Timeout,
    #[napi(value = "budget")]
    Budget,
    #[napi(value = "setup")]
    Setup,
    #[napi(value = "unknown")]
    Unknown,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum IsolationKind {
    #[napi(value = "none")]
    None,
    #[napi(value = "worktree")]
    Worktree,
    #[napi(value = "container")]
    Container,
    #[napi(value = "vm")]
    Vm,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum TemplateKind {
    #[napi(value = "vm_image")]
    VmImage,
    #[napi(value = "container_image")]
    ContainerImage,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum CapabilityKind {
    #[napi(value = "dispatch")]
    Dispatch,
    #[napi(value = "interact")]
    Interact,
    #[napi(value = "observe_stream")]
    ObserveStream,
    #[napi(value = "observe_poll")]
    ObservePoll,
    #[napi(value = "list_sessions")]
    ListSessions,
    #[napi(value = "resume")]
    Resume,
    #[napi(value = "cancel")]
    Cancel,
    #[napi(value = "teardown")]
    Teardown,
    #[napi(value = "isolation_worktree")]
    IsolationWorktree,
    #[napi(value = "isolation_container")]
    IsolationContainer,
    #[napi(value = "isolation_vm")]
    IsolationVm,
    #[napi(value = "templates")]
    Templates,
    #[napi(value = "artifact_fetch")]
    ArtifactFetch,
    #[napi(value = "usage_report")]
    UsageReport,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum EventKind {
    #[napi(value = "state")]
    State,
    #[napi(value = "message")]
    Message,
    #[napi(value = "tool_call")]
    ToolCall,
    #[napi(value = "tool_result")]
    ToolResult,
    #[napi(value = "log")]
    Log,
    #[napi(value = "usage")]
    Usage,
    #[napi(value = "artifact")]
    Artifact,
    #[napi(value = "raw")]
    Raw,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum Fidelity {
    #[napi(value = "exact")]
    Exact,
    #[napi(value = "derived")]
    Derived,
    #[napi(value = "scraped")]
    Scraped,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum ArtifactKind {
    #[napi(value = "branch")]
    Branch,
    #[napi(value = "pull_request")]
    PullRequest,
    #[napi(value = "patch")]
    Patch,
    #[napi(value = "file")]
    File,
    #[napi(value = "report")]
    Report,
    #[napi(value = "url")]
    Url,
}

#[napi(string_enum)]
#[derive(Clone, Copy)]
pub enum McpRole {
    #[napi(value = "supervisor")]
    Supervisor,
    #[napi(value = "worker")]
    Worker,
}

#[napi(object)]
#[derive(Clone)]
pub struct StateChange {
    pub from: SessionState,
    pub to: SessionState,
}

#[napi(object)]
#[derive(Clone)]
pub struct AgentMessage {
    pub role: String,
    pub text: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct ToolCallInfo {
    pub tool: String,
    pub input: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ToolResultInfo {
    pub tool: String,
    pub ok: bool,
    pub output: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct LogLine {
    pub line: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct UsageDelta {
    pub model_id: Option<String>,
    pub input_tokens: Option<i64>,
    pub output_tokens: Option<i64>,
    pub cost_cents: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ArtifactRef {
    pub artifact_idx: i64,
}

#[napi(object)]
#[derive(Clone)]
pub struct RawObservation {
    pub source: String,
    pub data: String,
}

#[napi(object)]
#[derive(Clone)]
pub struct OpenOptions {
    pub config_path: Option<String>,
    pub sink: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    pub agent: Option<String>,
    pub model: Option<String>,
    pub title: Option<String>,
    pub repo: Option<String>,
    pub git_ref: Option<String>,
    pub isolation: Option<IsolationKind>,
    pub template: Option<String>,
    pub setup: Option<String>,
    pub timeout_secs: Option<i32>,
    pub max_budget: Option<String>,
    pub unchecked: Option<bool>,
    pub labels: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct SessionFilter {
    pub env: Option<String>,
    pub state: Option<SessionState>,
    pub dispatch_id: Option<String>,
}

/// An editor link into a session's working directory.
#[napi(object)]
#[derive(Clone)]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    pub url: Option<String>,
    pub detail: Option<String>,
}

#[napi(object)]
#[derive(Clone)]
pub struct EventOptions {
    pub session_uid: Option<String>,
    pub after_idx: Option<i64>,
    pub kinds: Option<Vec<EventKind>>,
}

#[napi(object)]
#[derive(Clone)]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}

#[napi(object)]
#[derive(Clone)]
pub struct McpOptions {
    pub transport: Option<String>,
    pub role: Option<McpRole>,
    pub max_depth: Option<i32>,
}

#[napi(object)]
#[derive(Clone)]
pub struct DriverPlanOptions {
    pub dialect: Option<String>,
    pub tables: Option<Vec<String>>,
}

#[napi(object)]
#[derive(Clone)]
pub struct Statement {
    pub sql: String,
    pub params: String,
}

/// What an environment can do: one row per (env, capability) the catalog
/// advertises. Mirrors the env_capabilities edge as a flat, returnable value
/// struct (the closed CapabilityKind vocabulary, plus open detail).
#[napi(object)]
#[derive(Clone)]
pub struct EnvCapability {
    pub env_slug: String,
    pub capability: CapabilityKind,
    pub detail: Option<String>,
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[napi(object)]
#[derive(Clone)]
pub struct Environment {
    pub slug: String,
    pub kind: EnvKind,
    pub display_name: Option<String>,
    pub endpoint: Option<String>,
    pub last_probed_at: Option<String>,
}

/// env × agent × model availability (from the shipped catalog + config).
#[napi(object)]
#[derive(Clone)]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[napi(object)]
#[derive(Clone)]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: SessionState,
    pub env_handle: Option<String>,
    pub url: Option<String>,
    pub resumed_from: Option<String>,
    pub started_at: Option<String>,
    pub ended_at: Option<String>,
    pub exit_reason: Option<ExitReason>,
    pub exit_detail: Option<String>,
    pub reaped_at: Option<String>,
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[napi(object)]
#[derive(Clone)]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: EventKind,
    pub fidelity: Fidelity,
    pub payload: String,
}

/// The `Disponent` contract — implement over the engine in `crate::core_impl`.
pub trait DisponentCore: Sized + Send + Sync + 'static {
    fn open(options: Option<OpenOptions>) -> anyhow::Result<Self>;
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn capabilities(&self) -> anyhow::Result<Vec<EnvCapability>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    fn events(&self, options: Option<EventOptions>) -> anyhow::Result<Box<dyn PollStream<Event>>>;
    fn send(&self, session_uid: String, input: String) -> anyhow::Result<()>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
    ) -> anyhow::Result<Box<dyn PollStream<Statement>>>;
}

/// Poll-based stream from `Disponent.events` — call `next()` until it resolves null.
#[napi]
pub struct Events {
    stream: Arc<dyn PollStream<Event>>,
}
pub struct NextEventsTask {
    stream: Arc<dyn PollStream<Event>>,
}
impl Task for NextEventsTask {
    type Output = Option<Event>;
    type JsValue = Option<Event>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl Events {
    #[napi(ts_return_type = "Promise<Event | null>")]
    pub fn next(&self) -> AsyncTask<NextEventsTask> {
        AsyncTask::new(NextEventsTask {
            stream: self.stream.clone(),
        })
    }
}

/// Poll-based stream from `Disponent.driverPlan` — call `next()` until it resolves null.
#[napi]
pub struct DriverPlan {
    stream: Arc<dyn PollStream<Statement>>,
}
pub struct NextDriverPlanTask {
    stream: Arc<dyn PollStream<Statement>>,
}
impl Task for NextDriverPlanTask {
    type Output = Option<Statement>;
    type JsValue = Option<Statement>;
    fn compute(&mut self) -> Result<Self::Output> {
        loop {
            match self.stream.poll(Duration::from_millis(500)) {
                Poll::Item(v) => return Ok(Some(v)),
                Poll::Idle => continue,
                Poll::Closed => return Ok(None),
            }
        }
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}
#[napi]
impl DriverPlan {
    #[napi(ts_return_type = "Promise<Statement | null>")]
    pub fn next(&self) -> AsyncTask<NextDriverPlanTask> {
        AsyncTask::new(NextDriverPlanTask {
            stream: self.stream.clone(),
        })
    }
}

pub struct EnvironmentsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for EnvironmentsTask {
    type Output = Vec<Environment>;
    type JsValue = Vec<Environment>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.environments().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct RefreshTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    env_slug: Option<String>,
}
impl Task for RefreshTask {
    type Output = Vec<Environment>;
    type JsValue = Vec<Environment>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.refresh(self.env_slug.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct OfferingsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for OfferingsTask {
    type Output = Vec<Offering>;
    type JsValue = Vec<Offering>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.offerings().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CapabilitiesTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for CapabilitiesTask {
    type Output = Vec<EnvCapability>;
    type JsValue = Vec<EnvCapability>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.capabilities().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct DispatchTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    spec: DispatchSpec,
}
impl Task for DispatchTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.dispatch(self.spec.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SessionTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    uid: String,
}
impl Task for SessionTask {
    type Output = Option<Session>;
    type JsValue = Option<Session>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.session(self.uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SessionsTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    filter: Option<SessionFilter>,
}
impl Task for SessionsTask {
    type Output = Vec<Session>;
    type JsValue = Vec<Session>;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.sessions(self.filter.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct WorkspaceLinkTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for WorkspaceLinkTask {
    type Output = WorkspaceLink;
    type JsValue = WorkspaceLink;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core
            .workspace_link(self.session_uid.clone())
            .map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct SendTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
    input: String,
}
impl Task for SendTask {
    type Output = ();
    type JsValue = ();
    fn compute(&mut self) -> Result<Self::Output> {
        self.core
            .send(self.session_uid.clone(), self.input.clone())
            .map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct CancelTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for CancelTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.cancel(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ResumeTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for ResumeTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.resume(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ReapTask {
    core: Arc<crate::core_impl::DisponentImpl>,
    session_uid: String,
}
impl Task for ReapTask {
    type Output = Session;
    type JsValue = Session;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.reap(self.session_uid.clone()).map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

pub struct ReconcileTask {
    core: Arc<crate::core_impl::DisponentImpl>,
}
impl Task for ReconcileTask {
    type Output = ReconcileReport;
    type JsValue = ReconcileReport;
    fn compute(&mut self) -> Result<Self::Output> {
        self.core.reconcile().map_err(err)
    }
    fn resolve(&mut self, _env: Env, o: Self::Output) -> Result<Self::JsValue> {
        Ok(o)
    }
}

#[napi]
pub struct Disponent {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::DisponentImpl>,
}

#[napi]
impl Disponent {
    #[napi(constructor)]
    pub fn new(options: Option<OpenOptions>) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::DisponentImpl as DisponentCore>::open(options).map_err(err)?,
            ),
        })
    }
    #[napi(ts_return_type = "Promise<Environment[]>")]
    pub fn environments(&self) -> AsyncTask<EnvironmentsTask> {
        AsyncTask::new(EnvironmentsTask {
            core: self.core.clone(),
        })
    }
    #[napi(ts_return_type = "Promise<Environment[]>")]
    pub fn refresh(&self, env_slug: Option<String>) -> AsyncTask<RefreshTask> {
        AsyncTask::new(RefreshTask {
            core: self.core.clone(),
            env_slug,
        })
    }
    /// The offerings table: every env × agent × model the catalog knows, each
    /// flagged `isDefault` when it's the pick for a dispatch that names only the
    /// environment. Lets a consumer enumerate what can run where without reaching
    /// for the raw driver plan.
    #[napi(ts_return_type = "Promise<Offering[]>")]
    pub fn offerings(&self) -> AsyncTask<OfferingsTask> {
        AsyncTask::new(OfferingsTask {
            core: self.core.clone(),
        })
    }
    /// Per-env capabilities: what each environment can do, one row per
    /// (env, capability) the catalog advertises. Lets a consumer grade backends
    /// by what they support without reaching for the raw driver plan.
    #[napi(ts_return_type = "Promise<EnvCapability[]>")]
    pub fn capabilities(&self) -> AsyncTask<CapabilitiesTask> {
        AsyncTask::new(CapabilitiesTask {
            core: self.core.clone(),
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn dispatch(&self, spec: DispatchSpec) -> AsyncTask<DispatchTask> {
        AsyncTask::new(DispatchTask {
            core: self.core.clone(),
            spec,
        })
    }
    #[napi(ts_return_type = "Promise<Session | null>")]
    pub fn session(&self, uid: String) -> AsyncTask<SessionTask> {
        AsyncTask::new(SessionTask {
            core: self.core.clone(),
            uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session[]>")]
    pub fn sessions(&self, filter: Option<SessionFilter>) -> AsyncTask<SessionsTask> {
        AsyncTask::new(SessionsTask {
            core: self.core.clone(),
            filter,
        })
    }
    /// Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.
    #[napi(ts_return_type = "Promise<WorkspaceLink>")]
    pub fn workspace_link(&self, session_uid: String) -> AsyncTask<WorkspaceLinkTask> {
        AsyncTask::new(WorkspaceLinkTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi]
    pub fn events(&self, options: Option<EventOptions>) -> Result<Events> {
        Ok(Events {
            stream: Arc::from(self.core.events(options).map_err(err)?),
        })
    }
    #[napi(ts_return_type = "Promise<void>")]
    pub fn send(&self, session_uid: String, input: String) -> AsyncTask<SendTask> {
        AsyncTask::new(SendTask {
            core: self.core.clone(),
            session_uid,
            input,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn cancel(&self, session_uid: String) -> AsyncTask<CancelTask> {
        AsyncTask::new(CancelTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn resume(&self, session_uid: String) -> AsyncTask<ResumeTask> {
        AsyncTask::new(ResumeTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<Session>")]
    pub fn reap(&self, session_uid: String) -> AsyncTask<ReapTask> {
        AsyncTask::new(ReapTask {
            core: self.core.clone(),
            session_uid,
        })
    }
    #[napi(ts_return_type = "Promise<ReconcileReport>")]
    pub fn reconcile(&self) -> AsyncTask<ReconcileTask> {
        AsyncTask::new(ReconcileTask {
            core: self.core.clone(),
        })
    }
    #[napi]
    pub fn driver_plan(&self, options: Option<DriverPlanOptions>) -> Result<DriverPlan> {
        Ok(DriverPlan {
            stream: Arc::from(self.core.driver_plan(options).map_err(err)?),
        })
    }
    // @manual: wait — hand-written in lib.rs.
    // @manual: serveMcp — hand-written in lib.rs.
}
