//! GENERATED by fluessig mcp from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub isolation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fetch_remote: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_secs: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_budget: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unchecked: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionFilter {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dispatch_id: Option<String>,
}

/// An editor link into a session's working directory.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EventOptions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after_idx: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kinds: Option<Vec<String>>,
}

/// Where a Manager-sent message goes. A worker never fills this: the
/// worker-role server defaults recipient = its Manager, anchored to the bound
/// session (deferred to the MCP layer). A Manager sets exactly one destination.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SendTarget {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sessions: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

/// Filter for the `messages` read. Absent fields don't constrain.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MessagesFilter {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fanout_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latest_per_topic: Option<bool>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DriverPlanOptions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dialect: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tables: Option<Vec<String>>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Statement {
    pub sql: String,
    pub params: serde_json::Value,
}

/// What an environment can do: one row per (env, capability) the catalog
/// advertises. Mirrors the env_capabilities edge as a flat, returnable value
/// struct (the closed CapabilityKind vocabulary, plus open detail).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvCapability {
    pub env_slug: String,
    pub capability: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Environment {
    pub slug: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_probed_at: Option<String>,
}

/// env × agent × model availability (from the shipped catalog + config).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env_handle: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attach_tmux_socket: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attach_tmux_session: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resumed_from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reaped_at: Option<String>,
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: String,
    pub fidelity: String,
    pub payload: serde_json::Value,
}

/// One message dropped in one inbox — the manager↔worker communication
/// primitive (notes/manager-worker-comms.md). The Manager mints these addressed
/// to a worker or the user; a worker mints them addressed (implicitly) to its
/// Manager. Disponent owns these rows — no environment backs them, so reconcile
/// skips them and durability is the SQLite mirror (design §11).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    pub id: String,
    pub created_at: String,
    pub sender: String,
    pub recipient: String,
    pub session_uid: String,
    pub body: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<String>,
    pub fanout_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub acked_at: Option<String>,
}

/// The `Disponent` MCP contract — implement over the open engine.
pub trait DisponentMcp {
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn capabilities(&self) -> anyhow::Result<Vec<EnvCapability>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    /// One page of `events` (cursor: items after `after`, at most `limit`).
    fn events(
        &self,
        options: Option<EventOptions>,
        after: Option<i64>,
        limit: Option<u32>,
    ) -> anyhow::Result<Vec<Event>>;
    fn send(
        &self,
        body: String,
        to: Option<SendTarget>,
        in_reply_to: Option<String>,
        topic: Option<String>,
    ) -> anyhow::Result<Vec<Message>>;
    fn ack(&self, message_id: String) -> anyhow::Result<()>;
    fn messages(&self, filter: Option<MessagesFilter>) -> anyhow::Result<Vec<Message>>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    /// One page of `driverPlan` (cursor: items after `after`, at most `limit`).
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
        after: Option<i64>,
        limit: Option<u32>,
    ) -> anyhow::Result<Vec<Statement>>;
}

/// One JSON tool call → the trait call → the JSON result.
pub fn dispatch<T0: DisponentMcp>(
    disponent: &T0,
    tool: &str,
    args: &serde_json::Value,
) -> anyhow::Result<serde_json::Value> {
    match tool {
        "disponent_environments" => Ok(serde_json::to_value(disponent.environments()?)?),
        "disponent_refresh" => {
            let env_slug: Option<String> = opt_arg(args, "envSlug")?;
            Ok(serde_json::to_value(disponent.refresh(env_slug)?)?)
        }
        "disponent_offerings" => Ok(serde_json::to_value(disponent.offerings()?)?),
        "disponent_capabilities" => Ok(serde_json::to_value(disponent.capabilities()?)?),
        "disponent_dispatch" => {
            let spec: DispatchSpec = arg(args, "spec")?;
            Ok(serde_json::to_value(disponent.dispatch(spec)?)?)
        }
        "disponent_session" => {
            let uid: String = arg(args, "uid")?;
            Ok(serde_json::to_value(disponent.session(uid)?)?)
        }
        "disponent_sessions" => {
            let filter: Option<SessionFilter> = opt_arg(args, "filter")?;
            Ok(serde_json::to_value(disponent.sessions(filter)?)?)
        }
        "disponent_workspace_link" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(
                disponent.workspace_link(session_uid)?,
            )?)
        }
        "disponent_events" => {
            let options: Option<EventOptions> = opt_arg(args, "options")?;
            let after: Option<i64> = opt_arg(args, "after")?;
            let limit: Option<u32> = opt_arg(args, "limit")?;
            Ok(serde_json::to_value(
                disponent.events(options, after, limit)?,
            )?)
        }
        "disponent_send" => {
            let body: String = arg(args, "body")?;
            let to: Option<SendTarget> = opt_arg(args, "to")?;
            let in_reply_to: Option<String> = opt_arg(args, "inReplyTo")?;
            let topic: Option<String> = opt_arg(args, "topic")?;
            Ok(serde_json::to_value(disponent.send(
                body,
                to,
                in_reply_to,
                topic,
            )?)?)
        }
        "disponent_ack" => {
            let message_id: String = arg(args, "messageId")?;
            Ok(serde_json::to_value(disponent.ack(message_id)?)?)
        }
        "disponent_messages" => {
            let filter: Option<MessagesFilter> = opt_arg(args, "filter")?;
            Ok(serde_json::to_value(disponent.messages(filter)?)?)
        }
        "disponent_cancel" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.cancel(session_uid)?)?)
        }
        "disponent_resume" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.resume(session_uid)?)?)
        }
        "disponent_reap" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.reap(session_uid)?)?)
        }
        "disponent_reconcile" => Ok(serde_json::to_value(disponent.reconcile()?)?),
        "disponent_driver_plan" => {
            let options: Option<DriverPlanOptions> = opt_arg(args, "options")?;
            let after: Option<i64> = opt_arg(args, "after")?;
            let limit: Option<u32> = opt_arg(args, "limit")?;
            Ok(serde_json::to_value(
                disponent.driver_plan(options, after, limit)?,
            )?)
        }
        _ => anyhow::bail!("unknown tool: {tool}"),
    }
}

fn arg<T: serde::de::DeserializeOwned>(args: &serde_json::Value, name: &str) -> anyhow::Result<T> {
    let v = args
        .get(name)
        .ok_or_else(|| anyhow::anyhow!("missing required argument: {name}"))?;
    Ok(serde_json::from_value(v.clone()).map_err(|e| anyhow::anyhow!("argument {name}: {e}"))?)
}

fn opt_arg<T: serde::de::DeserializeOwned>(
    args: &serde_json::Value,
    name: &str,
) -> anyhow::Result<Option<T>> {
    match args.get(name) {
        None | Some(serde_json::Value::Null) => Ok(None),
        Some(v) => Ok(Some(
            serde_json::from_value(v.clone())
                .map_err(|e| anyhow::anyhow!("argument {name}: {e}"))?,
        )),
    }
}

/// The MCP tools manifest (name, description, inputSchema, annotations).
pub const TOOLS_JSON: &str = r###"{
  "tools": [
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_environments"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "envSlug": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "disponent_refresh"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "The offerings table: every env × agent × model the catalog knows, each\nflagged `isDefault` when it's the pick for a dispatch that names only the\nenvironment. Lets a consumer enumerate what can run where without reaching\nfor the raw driver plan.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_offerings"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "Per-env capabilities: what each environment can do, one row per\n(env, capability) the catalog advertises. Lets a consumer grade backends\nby what they support without reaching for the raw driver plan.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_capabilities"
    },
    {
      "description": "",
      "inputSchema": {
        "$defs": {
          "DispatchSpec": {
            "additionalProperties": false,
            "properties": {
              "agent": {
                "type": "string"
              },
              "brief": {
                "type": "string"
              },
              "env": {
                "type": "string"
              },
              "fetchRemote": {
                "type": "boolean"
              },
              "gitRef": {
                "type": "string"
              },
              "isolation": {
                "enum": [
                  "none",
                  "worktree",
                  "container",
                  "vm"
                ],
                "type": "string"
              },
              "labels": {
                "description": "opaque JSON"
              },
              "maxBudget": {
                "type": "string"
              },
              "model": {
                "type": "string"
              },
              "repo": {
                "type": "string"
              },
              "setup": {
                "type": "string"
              },
              "tags": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "template": {
                "type": "string"
              },
              "timeoutSecs": {
                "type": "integer"
              },
              "title": {
                "type": "string"
              },
              "unchecked": {
                "type": "boolean"
              }
            },
            "required": [
              "brief",
              "env"
            ],
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "spec": {
            "$ref": "#/$defs/DispatchSpec"
          }
        },
        "required": [
          "spec"
        ],
        "type": "object"
      },
      "name": "disponent_dispatch"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "uid": {
            "type": "string"
          }
        },
        "required": [
          "uid"
        ],
        "type": "object"
      },
      "name": "disponent_session"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "$defs": {
          "SessionFilter": {
            "additionalProperties": false,
            "properties": {
              "dispatchId": {
                "type": "string"
              },
              "env": {
                "type": "string"
              },
              "state": {
                "enum": [
                  "queued",
                  "provisioning",
                  "running",
                  "needs_input",
                  "completed",
                  "failed",
                  "cancelled",
                  "lost"
                ],
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "filter": {
            "$ref": "#/$defs/SessionFilter"
          }
        },
        "type": "object"
      },
      "name": "disponent_sessions"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_workspace_link"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "(Paged: pass `after` from the last item you saw; one page per call.)",
      "inputSchema": {
        "$defs": {
          "EventOptions": {
            "additionalProperties": false,
            "properties": {
              "afterIdx": {
                "type": "integer"
              },
              "kinds": {
                "items": {
                  "enum": [
                    "state",
                    "message",
                    "tool_call",
                    "tool_result",
                    "log",
                    "usage",
                    "artifact",
                    "raw",
                    "mail"
                  ],
                  "type": "string"
                },
                "type": "array"
              },
              "sessionUid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "after": {
            "description": "resume cursor: return items after this index",
            "type": "integer"
          },
          "limit": {
            "description": "max items in this page",
            "type": "integer"
          },
          "options": {
            "$ref": "#/$defs/EventOptions"
          }
        },
        "type": "object"
      },
      "name": "disponent_events"
    },
    {
      "description": "The one messaging primitive (notes/manager-worker-comms.md §6). A Manager\n`to` names a tagged worker subset (fan-out) or the user; recipients resolve\nat send time to a concrete list (a snapshot, never kept live). One Message\nis minted per matched session, all sharing a freshly minted `fanoutId`;\n`topic` (optional) is the supersession key for latest-wins (§7). Returns the\nMessages minted. Delivery is the reader's `events` pull; a message to a\nconcrete live worker is also delivered best-effort to its prompt on an\ninteract-capable env (the legacy `send` behavior, now one backend delivery).\nWorker self-send (recipient forced to the Manager) is a worker-role MCP\nconcern, deferred — the core send is the Manager surface.",
      "inputSchema": {
        "$defs": {
          "SendTarget": {
            "additionalProperties": false,
            "description": "Where a Manager-sent message goes. A worker never fills this: the\nworker-role server defaults recipient = its Manager, anchored to the bound\nsession (deferred to the MCP layer). A Manager sets exactly one destination.",
            "properties": {
              "sessions": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "tags": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "user": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "body": {
            "type": "string"
          },
          "inReplyTo": {
            "type": "string"
          },
          "to": {
            "$ref": "#/$defs/SendTarget"
          },
          "topic": {
            "type": "string"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      },
      "name": "disponent_send"
    },
    {
      "description": "Acknowledge a message you received (received/handled): stamps `ackedAt`,\nwhich the Manager observes across a `fanoutId` to see \"N of M acted\" (§7).\nIdempotent.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "messageId": {
            "type": "string"
          }
        },
        "required": [
          "messageId"
        ],
        "type": "object"
      },
      "name": "disponent_ack"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "Read Messages, filtered. The Manager's fan-out ack-progress view\n(`{fanoutId}`) and a recipient's inbox (`{recipient, sessionUid}`, optionally\n`latestPerTopic` for the read-side latest-wins collapse, §7).",
      "inputSchema": {
        "$defs": {
          "MessagesFilter": {
            "additionalProperties": false,
            "description": "Filter for the `messages` read. Absent fields don't constrain.",
            "properties": {
              "fanoutId": {
                "type": "string"
              },
              "latestPerTopic": {
                "type": "boolean"
              },
              "recipient": {
                "enum": [
                  "manager",
                  "worker",
                  "user"
                ],
                "type": "string"
              },
              "sessionUid": {
                "type": "string"
              },
              "topic": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "filter": {
            "$ref": "#/$defs/MessagesFilter"
          }
        },
        "type": "object"
      },
      "name": "disponent_messages"
    },
    {
      "annotations": {
        "destructiveHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_cancel"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_resume"
    },
    {
      "annotations": {
        "destructiveHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_reap"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_reconcile"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "(Paged: pass `after` from the last item you saw; one page per call.)",
      "inputSchema": {
        "$defs": {
          "DriverPlanOptions": {
            "additionalProperties": false,
            "properties": {
              "dialect": {
                "type": "string"
              },
              "tables": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "after": {
            "description": "resume cursor: return items after this index",
            "type": "integer"
          },
          "limit": {
            "description": "max items in this page",
            "type": "integer"
          },
          "options": {
            "$ref": "#/$defs/DriverPlanOptions"
          }
        },
        "type": "object"
      },
      "name": "disponent_driver_plan"
    }
  ]
}"###;
