//! GENERATED by fluessig mcp from disponent.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated code repeats by design.
#![allow(clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchSpec {
    pub brief: String,
    pub env: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub isolation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub setup: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_secs: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_budget: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unchecked: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionFilter {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dispatch_id: Option<String>,
}

/// An editor link into a session's working directory.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceLink {
    pub session_uid: String,
    pub available: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EventOptions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after_idx: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kinds: Option<Vec<String>>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReconcileReport {
    pub adopted: i32,
    pub confirmed: i32,
    pub lost: i32,
    pub torn_down: i32,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DriverPlanOptions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dialect: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tables: Option<Vec<String>>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Statement {
    pub sql: String,
    pub params: serde_json::Value,
}

/// Somewhere work can run. Config supplies these; the shipped catalog fills offerings + capabilities.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Environment {
    pub slug: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_probed_at: Option<String>,
}

/// env × agent × model availability (from the shipped catalog + config).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Offering {
    pub env_slug: String,
    pub agent_name: String,
    pub model_id: String,
    pub is_default: bool,
}

/// One attempt at a dispatch, mirroring one env-side resource.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Session {
    pub uid: String,
    pub dispatch_id: String,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env_handle: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resumed_from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reaped_at: Option<String>,
}

/// One observation on a session's timeline (containment rides the key: the
/// session FK + the position, like Artifact/Usage — to-manys are queries).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Event {
    pub session_uid: String,
    pub idx: i64,
    pub ts: String,
    pub kind: String,
    pub fidelity: String,
    pub payload: serde_json::Value,
}

/// The `Disponent` MCP contract — implement over the open engine.
pub trait DisponentMcp {
    fn environments(&self) -> anyhow::Result<Vec<Environment>>;
    fn refresh(&self, env_slug: Option<String>) -> anyhow::Result<Vec<Environment>>;
    fn offerings(&self) -> anyhow::Result<Vec<Offering>>;
    fn dispatch(&self, spec: DispatchSpec) -> anyhow::Result<Session>;
    fn session(&self, uid: String) -> anyhow::Result<Option<Session>>;
    fn sessions(&self, filter: Option<SessionFilter>) -> anyhow::Result<Vec<Session>>;
    fn workspace_link(&self, session_uid: String) -> anyhow::Result<WorkspaceLink>;
    /// One page of `events` (cursor: items after `after`, at most `limit`).
    fn events(
        &self,
        options: Option<EventOptions>,
        after: Option<i64>,
        limit: Option<u32>,
    ) -> anyhow::Result<Vec<Event>>;
    fn send(&self, session_uid: String, input: String) -> anyhow::Result<()>;
    fn cancel(&self, session_uid: String) -> anyhow::Result<Session>;
    fn resume(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reap(&self, session_uid: String) -> anyhow::Result<Session>;
    fn reconcile(&self) -> anyhow::Result<ReconcileReport>;
    /// One page of `driverPlan` (cursor: items after `after`, at most `limit`).
    fn driver_plan(
        &self,
        options: Option<DriverPlanOptions>,
        after: Option<i64>,
        limit: Option<u32>,
    ) -> anyhow::Result<Vec<Statement>>;
}

/// One JSON tool call → the trait call → the JSON result.
pub fn dispatch<T0: DisponentMcp>(
    disponent: &T0,
    tool: &str,
    args: &serde_json::Value,
) -> anyhow::Result<serde_json::Value> {
    match tool {
        "disponent_environments" => Ok(serde_json::to_value(disponent.environments()?)?),
        "disponent_refresh" => {
            let env_slug: Option<String> = opt_arg(args, "envSlug")?;
            Ok(serde_json::to_value(disponent.refresh(env_slug)?)?)
        }
        "disponent_offerings" => Ok(serde_json::to_value(disponent.offerings()?)?),
        "disponent_dispatch" => {
            let spec: DispatchSpec = arg(args, "spec")?;
            Ok(serde_json::to_value(disponent.dispatch(spec)?)?)
        }
        "disponent_session" => {
            let uid: String = arg(args, "uid")?;
            Ok(serde_json::to_value(disponent.session(uid)?)?)
        }
        "disponent_sessions" => {
            let filter: Option<SessionFilter> = opt_arg(args, "filter")?;
            Ok(serde_json::to_value(disponent.sessions(filter)?)?)
        }
        "disponent_workspace_link" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(
                disponent.workspace_link(session_uid)?,
            )?)
        }
        "disponent_events" => {
            let options: Option<EventOptions> = opt_arg(args, "options")?;
            let after: Option<i64> = opt_arg(args, "after")?;
            let limit: Option<u32> = opt_arg(args, "limit")?;
            Ok(serde_json::to_value(
                disponent.events(options, after, limit)?,
            )?)
        }
        "disponent_send" => {
            let session_uid: String = arg(args, "sessionUid")?;
            let input: String = arg(args, "input")?;
            Ok(serde_json::to_value(disponent.send(session_uid, input)?)?)
        }
        "disponent_cancel" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.cancel(session_uid)?)?)
        }
        "disponent_resume" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.resume(session_uid)?)?)
        }
        "disponent_reap" => {
            let session_uid: String = arg(args, "sessionUid")?;
            Ok(serde_json::to_value(disponent.reap(session_uid)?)?)
        }
        "disponent_reconcile" => Ok(serde_json::to_value(disponent.reconcile()?)?),
        "disponent_driver_plan" => {
            let options: Option<DriverPlanOptions> = opt_arg(args, "options")?;
            let after: Option<i64> = opt_arg(args, "after")?;
            let limit: Option<u32> = opt_arg(args, "limit")?;
            Ok(serde_json::to_value(
                disponent.driver_plan(options, after, limit)?,
            )?)
        }
        _ => anyhow::bail!("unknown tool: {tool}"),
    }
}

fn arg<T: serde::de::DeserializeOwned>(args: &serde_json::Value, name: &str) -> anyhow::Result<T> {
    let v = args
        .get(name)
        .ok_or_else(|| anyhow::anyhow!("missing required argument: {name}"))?;
    Ok(serde_json::from_value(v.clone()).map_err(|e| anyhow::anyhow!("argument {name}: {e}"))?)
}

fn opt_arg<T: serde::de::DeserializeOwned>(
    args: &serde_json::Value,
    name: &str,
) -> anyhow::Result<Option<T>> {
    match args.get(name) {
        None | Some(serde_json::Value::Null) => Ok(None),
        Some(v) => Ok(Some(
            serde_json::from_value(v.clone())
                .map_err(|e| anyhow::anyhow!("argument {name}: {e}"))?,
        )),
    }
}

/// The MCP tools manifest (name, description, inputSchema, annotations).
pub const TOOLS_JSON: &str = r###"{
  "tools": [
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_environments"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "envSlug": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "disponent_refresh"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "The offerings table: every env × agent × model the catalog knows, each\nflagged `isDefault` when it's the pick for a dispatch that names only the\nenvironment. Lets a consumer enumerate what can run where without reaching\nfor the raw driver plan.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_offerings"
    },
    {
      "description": "",
      "inputSchema": {
        "$defs": {
          "DispatchSpec": {
            "additionalProperties": false,
            "properties": {
              "agent": {
                "type": "string"
              },
              "brief": {
                "type": "string"
              },
              "env": {
                "type": "string"
              },
              "gitRef": {
                "type": "string"
              },
              "isolation": {
                "enum": [
                  "none",
                  "worktree",
                  "container",
                  "vm"
                ],
                "type": "string"
              },
              "labels": {
                "description": "opaque JSON"
              },
              "maxBudget": {
                "type": "string"
              },
              "model": {
                "type": "string"
              },
              "repo": {
                "type": "string"
              },
              "setup": {
                "type": "string"
              },
              "template": {
                "type": "string"
              },
              "timeoutSecs": {
                "type": "integer"
              },
              "title": {
                "type": "string"
              },
              "unchecked": {
                "type": "boolean"
              }
            },
            "required": [
              "brief",
              "env"
            ],
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "spec": {
            "$ref": "#/$defs/DispatchSpec"
          }
        },
        "required": [
          "spec"
        ],
        "type": "object"
      },
      "name": "disponent_dispatch"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "uid": {
            "type": "string"
          }
        },
        "required": [
          "uid"
        ],
        "type": "object"
      },
      "name": "disponent_session"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "",
      "inputSchema": {
        "$defs": {
          "SessionFilter": {
            "additionalProperties": false,
            "properties": {
              "dispatchId": {
                "type": "string"
              },
              "env": {
                "type": "string"
              },
              "state": {
                "enum": [
                  "queued",
                  "provisioning",
                  "running",
                  "needs_input",
                  "completed",
                  "failed",
                  "cancelled",
                  "lost"
                ],
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "filter": {
            "$ref": "#/$defs/SessionFilter"
          }
        },
        "type": "object"
      },
      "name": "disponent_sessions"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "Return an editor link (VS Code deep link) into the session's working directory, when the backend can honestly provide one.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_workspace_link"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "(Paged: pass `after` from the last item you saw; one page per call.)",
      "inputSchema": {
        "$defs": {
          "EventOptions": {
            "additionalProperties": false,
            "properties": {
              "afterIdx": {
                "type": "integer"
              },
              "kinds": {
                "items": {
                  "enum": [
                    "state",
                    "message",
                    "tool_call",
                    "tool_result",
                    "log",
                    "usage",
                    "artifact",
                    "raw"
                  ],
                  "type": "string"
                },
                "type": "array"
              },
              "sessionUid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "after": {
            "description": "resume cursor: return items after this index",
            "type": "integer"
          },
          "limit": {
            "description": "max items in this page",
            "type": "integer"
          },
          "options": {
            "$ref": "#/$defs/EventOptions"
          }
        },
        "type": "object"
      },
      "name": "disponent_events"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "input": {
            "type": "string"
          },
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid",
          "input"
        ],
        "type": "object"
      },
      "name": "disponent_send"
    },
    {
      "annotations": {
        "destructiveHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_cancel"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_resume"
    },
    {
      "annotations": {
        "destructiveHint": true
      },
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "sessionUid": {
            "type": "string"
          }
        },
        "required": [
          "sessionUid"
        ],
        "type": "object"
      },
      "name": "disponent_reap"
    },
    {
      "description": "",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "disponent_reconcile"
    },
    {
      "annotations": {
        "readOnlyHint": true
      },
      "description": "(Paged: pass `after` from the last item you saw; one page per call.)",
      "inputSchema": {
        "$defs": {
          "DriverPlanOptions": {
            "additionalProperties": false,
            "properties": {
              "dialect": {
                "type": "string"
              },
              "tables": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              }
            },
            "type": "object"
          }
        },
        "additionalProperties": false,
        "properties": {
          "after": {
            "description": "resume cursor: return items after this index",
            "type": "integer"
          },
          "limit": {
            "description": "max items in this page",
            "type": "integer"
          },
          "options": {
            "$ref": "#/$defs/DriverPlanOptions"
          }
        },
        "type": "object"
      },
      "name": "disponent_driver_plan"
    }
  ]
}"###;
