//! GENERATED by fluessig from disponent.tsp — DO NOT EDIT.
//!
//! The schema as code: per-dialect DDL templates (`__table__` is
//! substituted with the possibly-renamed target name, matching the sink
//! convention) + primary keys, lowered from the fluessig catalog.
//!
//! straitjacket-allow-file:duplication — generated code repeats by design.

/// One table's schema, as code.
pub struct TableSchema {
    pub name: &'static str,
    pub pk: &'static [&'static str],
    pub ddl: &'static str,
}

/// The Postgres projection of every physical table in the catalog.
pub const PG_TABLES: &[TableSchema] = &[
    TableSchema {
        name: "agents",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "version" text
);
"#,
    },
    TableSchema {
        name: "artifacts",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" bigint NOT NULL,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "meta" text,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "capabilities",
        pk: &["capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "capability" text PRIMARY KEY
);
"#,
    },
    TableSchema {
        name: "dispatches",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" timestamptz NOT NULL,
  "title" text,
  "brief" text NOT NULL,
  "repo" text,
  "git_ref" text,
  "isolation" text NOT NULL,
  "fetch_remote" boolean,
  "template_name" text,
  "setup" text,
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text,
  "timeout_secs" integer,
  "max_budget" numeric,
  "via_mcp_depth" integer NOT NULL,
  "tags" jsonb,
  "labels" text
);
"#,
    },
    TableSchema {
        name: "env_capabilities",
        pk: &["slug", "detail", "capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text NOT NULL,
  "detail" text,
  "capability" text NOT NULL,
  PRIMARY KEY ("slug", "detail", "capability")
);
"#,
    },
    TableSchema {
        name: "environments",
        pk: &["slug"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text PRIMARY KEY,
  "kind" text NOT NULL,
  "display_name" text,
  "endpoint" text,
  "last_probed_at" timestamptz
);
"#,
    },
    TableSchema {
        name: "events",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" bigint NOT NULL,
  "ts" timestamptz NOT NULL,
  "kind" text NOT NULL,
  "fidelity" text NOT NULL,
  "payload_kind" text NOT NULL,
  "payload" jsonb NOT NULL,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "messages",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" timestamptz NOT NULL,
  "sender" text NOT NULL,
  "recipient" text NOT NULL,
  "session_uid" text NOT NULL,
  "body" text NOT NULL,
  "in_reply_to" text,
  "fanout_id" text NOT NULL,
  "topic" text,
  "acked_at" timestamptz
);
"#,
    },
    TableSchema {
        name: "models",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "provider" text,
  "family" text
);
"#,
    },
    TableSchema {
        name: "offerings",
        pk: &["env_slug", "agent_name", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text NOT NULL,
  "is_default" boolean NOT NULL,
  PRIMARY KEY ("env_slug", "agent_name", "model_id")
);
"#,
    },
    TableSchema {
        name: "sessions",
        pk: &["uid"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "uid" text PRIMARY KEY,
  "dispatch_id" text NOT NULL,
  "state" text NOT NULL,
  "env_handle" text,
  "attach_tmux_socket" text,
  "attach_tmux_session" text,
  "url" text,
  "resumed_from" text,
  "started_at" timestamptz,
  "ended_at" timestamptz,
  "exit_reason" text,
  "exit_detail" text,
  "reaped_at" timestamptz
);
"#,
    },
    TableSchema {
        name: "templates",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "setup" text,
  "note" text
);
"#,
    },
    TableSchema {
        name: "usage",
        pk: &["session_uid", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "model_id" text NOT NULL,
  "input_tokens" bigint NOT NULL,
  "output_tokens" bigint NOT NULL,
  "cost_cents" numeric NOT NULL,
  PRIMARY KEY ("session_uid", "model_id")
);
"#,
    },
];

/// The Sqlite projection of every physical table in the catalog.
pub const SQLITE_TABLES: &[TableSchema] = &[
    TableSchema {
        name: "agents",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "version" text
);
"#,
    },
    TableSchema {
        name: "artifacts",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" integer NOT NULL,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "meta" text,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "capabilities",
        pk: &["capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "capability" text PRIMARY KEY
);
"#,
    },
    TableSchema {
        name: "dispatches",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" text NOT NULL,
  "title" text,
  "brief" text NOT NULL,
  "repo" text,
  "git_ref" text,
  "isolation" text NOT NULL,
  "fetch_remote" integer,
  "template_name" text,
  "setup" text,
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text,
  "timeout_secs" integer,
  "max_budget" numeric,
  "via_mcp_depth" integer NOT NULL,
  "tags" text,
  "labels" text
);
"#,
    },
    TableSchema {
        name: "env_capabilities",
        pk: &["slug", "detail", "capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text NOT NULL,
  "detail" text,
  "capability" text NOT NULL,
  PRIMARY KEY ("slug", "detail", "capability")
);
"#,
    },
    TableSchema {
        name: "environments",
        pk: &["slug"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text PRIMARY KEY,
  "kind" text NOT NULL,
  "display_name" text,
  "endpoint" text,
  "last_probed_at" text
);
"#,
    },
    TableSchema {
        name: "events",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" integer NOT NULL,
  "ts" text NOT NULL,
  "kind" text NOT NULL,
  "fidelity" text NOT NULL,
  "payload_kind" text NOT NULL,
  "payload" text NOT NULL,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "messages",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" text NOT NULL,
  "sender" text NOT NULL,
  "recipient" text NOT NULL,
  "session_uid" text NOT NULL,
  "body" text NOT NULL,
  "in_reply_to" text,
  "fanout_id" text NOT NULL,
  "topic" text,
  "acked_at" text
);
"#,
    },
    TableSchema {
        name: "models",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "provider" text,
  "family" text
);
"#,
    },
    TableSchema {
        name: "offerings",
        pk: &["env_slug", "agent_name", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text NOT NULL,
  "is_default" integer NOT NULL,
  PRIMARY KEY ("env_slug", "agent_name", "model_id")
);
"#,
    },
    TableSchema {
        name: "sessions",
        pk: &["uid"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "uid" text PRIMARY KEY,
  "dispatch_id" text NOT NULL,
  "state" text NOT NULL,
  "env_handle" text,
  "attach_tmux_socket" text,
  "attach_tmux_session" text,
  "url" text,
  "resumed_from" text,
  "started_at" text,
  "ended_at" text,
  "exit_reason" text,
  "exit_detail" text,
  "reaped_at" text
);
"#,
    },
    TableSchema {
        name: "templates",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "setup" text,
  "note" text
);
"#,
    },
    TableSchema {
        name: "usage",
        pk: &["session_uid", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "model_id" text NOT NULL,
  "input_tokens" integer NOT NULL,
  "output_tokens" integer NOT NULL,
  "cost_cents" numeric NOT NULL,
  PRIMARY KEY ("session_uid", "model_id")
);
"#,
    },
];

/// The Duckdb projection of every physical table in the catalog.
pub const DUCKDB_TABLES: &[TableSchema] = &[
    TableSchema {
        name: "agents",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "version" text
);
"#,
    },
    TableSchema {
        name: "artifacts",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" bigint NOT NULL,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "meta" text,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "capabilities",
        pk: &["capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "capability" text PRIMARY KEY
);
"#,
    },
    TableSchema {
        name: "dispatches",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" timestamp NOT NULL,
  "title" text,
  "brief" text NOT NULL,
  "repo" text,
  "git_ref" text,
  "isolation" text NOT NULL,
  "fetch_remote" boolean,
  "template_name" text,
  "setup" text,
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text,
  "timeout_secs" integer,
  "max_budget" numeric,
  "via_mcp_depth" integer NOT NULL,
  "tags" json,
  "labels" text
);
"#,
    },
    TableSchema {
        name: "env_capabilities",
        pk: &["slug", "detail", "capability"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text NOT NULL,
  "detail" text,
  "capability" text NOT NULL,
  PRIMARY KEY ("slug", "detail", "capability")
);
"#,
    },
    TableSchema {
        name: "environments",
        pk: &["slug"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "slug" text PRIMARY KEY,
  "kind" text NOT NULL,
  "display_name" text,
  "endpoint" text,
  "last_probed_at" timestamp
);
"#,
    },
    TableSchema {
        name: "events",
        pk: &["session_uid", "idx"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "idx" bigint NOT NULL,
  "ts" timestamp NOT NULL,
  "kind" text NOT NULL,
  "fidelity" text NOT NULL,
  "payload_kind" text NOT NULL,
  "payload" json NOT NULL,
  PRIMARY KEY ("session_uid", "idx")
);
"#,
    },
    TableSchema {
        name: "messages",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "created_at" timestamp NOT NULL,
  "sender" text NOT NULL,
  "recipient" text NOT NULL,
  "session_uid" text NOT NULL,
  "body" text NOT NULL,
  "in_reply_to" text,
  "fanout_id" text NOT NULL,
  "topic" text,
  "acked_at" timestamp
);
"#,
    },
    TableSchema {
        name: "models",
        pk: &["id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "id" text PRIMARY KEY,
  "provider" text,
  "family" text
);
"#,
    },
    TableSchema {
        name: "offerings",
        pk: &["env_slug", "agent_name", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "env_slug" text NOT NULL,
  "agent_name" text NOT NULL,
  "model_id" text NOT NULL,
  "is_default" boolean NOT NULL,
  PRIMARY KEY ("env_slug", "agent_name", "model_id")
);
"#,
    },
    TableSchema {
        name: "sessions",
        pk: &["uid"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "uid" text PRIMARY KEY,
  "dispatch_id" text NOT NULL,
  "state" text NOT NULL,
  "env_handle" text,
  "attach_tmux_socket" text,
  "attach_tmux_session" text,
  "url" text,
  "resumed_from" text,
  "started_at" timestamp,
  "ended_at" timestamp,
  "exit_reason" text,
  "exit_detail" text,
  "reaped_at" timestamp
);
"#,
    },
    TableSchema {
        name: "templates",
        pk: &["name"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "name" text PRIMARY KEY,
  "kind" text NOT NULL,
  "locator" text NOT NULL,
  "setup" text,
  "note" text
);
"#,
    },
    TableSchema {
        name: "usage",
        pk: &["session_uid", "model_id"],
        ddl: r#"CREATE TABLE IF NOT EXISTS "__table__" (
  "session_uid" text NOT NULL,
  "model_id" text NOT NULL,
  "input_tokens" bigint NOT NULL,
  "output_tokens" bigint NOT NULL,
  "cost_cents" numeric NOT NULL,
  PRIMARY KEY ("session_uid", "model_id")
);
"#,
    },
];

/// Every BOOLEAN `(table, column)` in the schema — for coercing SQLite's 0/1.
pub const BOOL_COLUMNS: &[(&str, &str)] =
    &[("dispatches", "fetch_remote"), ("offerings", "is_default")];
